const { writeFileSync } = require("fs")

const allIcons = [
    "Search",
    "Search",
    "Home",
    "Menu",
    "Close",
    "Settings",
    "Done",
    "Expand More",
    "Check Circle",
    "Favorite",
    "Add",
    "Delete",
    "Arrow Back",
    "Star",
    "Chevron Right",
    "Logout",
    "Arrow Forward iOS",
    "Add Circle",
    "Cancel",
    "Arrow Back iOS",
    "Arrow Forward",
    "Arrow Drop Down",
    "More Vert",
    "Check",
    "Check Box",
    "Toggle On",
    "Grade",
    "Open In New",
    "Refresh",
    "Check Box Outline Blank",
    "Login",
    "Chevron Left",
    "Expand Less",
    "Radio Button Unchecked",
    "More Horiz",
    "Apps",
    "Download",
    "Arrow Right Alt",
    "Radio Button Checked",
    "Remove",
    "Bolt",
    "Toggle Off",
    "Arrow Upward",
    "Filter List",
    "Delete Forever",
    "Autorenew",
    "Key",
    "Sync",
    "Arrow Downward",
    "Block",
    "Sort",
    "Add Box",
    "Arrow Back iOS New",
    "Restart Alt",
    "Shopping Cart Checkout",
    "Menu Open",
    "Expand Circle Down",
    "Backspace",
    "Undo",
    "Arrow Circle Right",
    "Done All",
    "Arrow Right",
    "Do Not Disturb On",
    "Open In Full",
    "Manage Search",
    "Double Arrow",
    "Sync Alt",
    "Zoom In",
    "Done Outline",
    "Drag Indicator",
    "Fullscreen",
    "Keyboard Double Arrow Right",
    "Star Half",
    "Settings Accessibility",
    "iOS Share",
    "Arrow Drop Up",
    "Reply",
    "Exit To App",
    "Unfold More",
    "Library Add",
    "Cached",
    "Terminal",
    "Select Check Box",
    "Change Circle",
    "Disabled By Default",
    "Swap Horiz",
    "Swap Vert",
    "Close Fullscreen",
    "App Registration",
    "Download For Offline",
    "Arrow Circle Left",
    "Arrow Circle Up",
    "File Open",
    "Minimize",
    "Dataset",
    "Open With",
    "Keyboard Double Arrow Left",
    "Add Task",
    "Start",
    "Keyboard Voice",
    "Keyboard Double Arrow Down",
    "Create New Folder",
    "Forward",
    "Downloading",
    "Settings Applications",
    "Upload",
    "Compare Arrows",
    "Redo",
    "Publish",
    "Zoom Out",
    "Arrow Left",
    "HTML",
    "Token",
    "Switch Access Shortcut",
    "Fullscreen Exit",
    "Arrow Circle Down",
    "Sort By Alpha",
    "Delete Sweep",
    "Indeterminate Check Box",
    "First Page",
    "View Timeline",
    "Keyboard Double Arrow Up",
    "Settings Backup Restore",
    "Arrow Drop Down Circle",
    "Assistant Navigation",
    "Sync Problem",
    "Clear All",
    "Density Medium",
    "Heart Plus",
    "Expand",
    "Filter Alt Off",
    "Last Page",
    "Subdirectory Arrow Right",
    "Unfold Less",
    "Arrow Outward",
    "Download Done",
    "123",
    "Swipe Left",
    "Saved Search",
    "System Update Alt",
    "Place Item",
    "Search Off",
    "Output",
    "Maximize",
    "Javascript",
    "Swipe Up",
    "Fit Screen",
    "Select All",
    "Hide Source",
    "Dynamic Form",
    "Swipe Right",
    "Check Small",
    "Switch Access Shortcut Add",
    "Browse Gallery",
    "Density Small",
    "CSS",
    "Assistant Direction",
    "File Download Done",
    "Move Up",
    "Youtube Searched For",
    "Swap Horizontal Circle",
    "Data Thresholding",
    "Install Mobile",
    "Abc",
    "Dataset Linked",
    "Move Down",
    "Restore From Trash",
    "Enable",
    "Install Desktop",
    "Keyboard Command Key",
    "View Kanban",
    "Browse Activity",
    "Reply All",
    "Switch Left",
    "Compress",
    "Swipe Down",
    "Swap Vertical Circle",
    "Remove Done",
    "Apps Outage",
    "Filter List Off",
    "Star Rate",
    "Hide",
    "Switch Right",
    "Swipe Vertical",
    "More Up",
    "Sync Disabled",
    "Pinch",
    "Keyboard Control Key",
    "Eject",
    "Key Off",
    "PHP",
    "Subdirectory Arrow Left",
    "View Cozy",
    "Transcribe",
    "Do Not Disturb Off",
    "Send Time Extension",
    "Width Normal",
    "View Comfy Alt",
    "Heart Minus",
    "Share Reviews",
    "Width Full",
    "Unfold More Double",
    "File Download Off",
    "View Compact Alt",
    "Extension Off",
    "Open In New Off",
    "Check Indeterminate Small",
    "More Down",
    "Width Wide",
    "Repartition",
    "Density Large",
    "Swipe Left Alt",
    "Swipe Down Alt",
    "Swipe Up Alt",
    "Swipe Right Alt",
    "Unfold Less Double",
    "Cycle",
    "Progress Activity",
    "Keyboard Option Key",
    "HLS",
    "HLS Off",
    "File Upload Off",
    "Expand Content",
    "Rebase",
    "Expand All",
    "Collapse All",
    "Rebase Edit",
    "Quick Reference All",
    "Arrow Split",
    "Deployed Code",
    "Empty Dashboard",
    "Stack",
    "Stat 0",
    "Acute",
    "Arrow Upward Alt",
    "Switches",
    "Data Check",
    "Left Click",
    "Arrow Downward Alt",
    "Directory Sync",
    "Data Alert",
    "Quick Reference",
    "Page Info",
    "Sync Saved Locally",
    "Cards",
    "Side Navigation",
    "Clock Loader 60",
    "Data Info Alert",
    "Bubble",
    "Question Exchange",
    "Steppers",
    "Move Item",
    "Point Scan",
    "Stack Star",
    "Arrow Left Alt",
    "Preliminary",
    "Stat 3",
    "Captive Portal",
    "Search Check",
    "Star Rate Half",
    "Unknown Med",
    "Toolbar",
    "Right Panel Close",
    "New Window",
    "Clock Loader 10",
    "Right Panel Open",
    "Rule Settings",
    "Sweep",
    "Responsive Layout",
    "Step",
    "Patient List",
    "Drag Pan",
    "Clock Loader 40",
    "Expand Circle Right",
    "Share Windows",
    "Stat Minus 1",
    "Arrow Insert",
    "Left Panel Close",
    "Page Control",
    "Dialogs",
    "Expand Circle Up",
    "Input Circle",
    "Heart Check",
    "Move Group",
    "Stat 2",
    "Stat Minus 2",
    "Capture",
    "Left Panel Open",
    "Clock Loader 80",
    "Step Into",
    "All Match",
    "Bottom Panel Open",
    "Clock Loader 90",
    "Resize",
    "Stack Off",
    "Stat 1",
    "Magnification Small",
    "Partner Reports",
    "Deployed Code Update",
    "Dropdown",
    "Magnification Large",
    "Bottom Navigation",
    "Clock Loader 20",
    "Event List",
    "Sliders",
    "Radio Button Partial",
    "Bottom Drawer",
    "Buttons Alt",
    "Chronic",
    "Drag Click",
    "Go To Line",
    "Pip",
    "Shelf Position",
    "Stat Minus 3",
    "Tabs",
    "Arrow And Edge",
    "Bottom Sheets",
    "Open In New Down",
    "Step Over",
    "Arrow Range",
    "Chip Extraction",
    "Iframe",
    "Right Click",
    "Unknown 5",
    "Ripples",
    "Move Selection Left",
    "Toast",
    "Linked Services",
    "Reopen Window",
    "Subheader",
    "Arrow Or Edge",
    "Chips",
    "Output Circle",
    "Switch Access",
    "Arrows Outward",
    "Bottom Right Click",
    "Step Out",
    "App Badging",
    "Arrow Top Left",
    "Back To Tab",
    "Pip Exit",
    "Key Vertical",
    "Amend",
    "Error Med",
    "Jump To Element",
    "Move Selection Right",
    "Move Selection Up",
    "Arrow Top Right",
    "Bubbles",
    "Deployed Code History",
    "Position Top Right",
    "Deployed Code Alert",
    "Position Bottom Right",
    "Shelf Auto Hide",
    "Stacks",
    "Bottom App Bar",
    "Bottom Panel Close",
    "Iframe Off",
    "Highlight Mouse Cursor",
    "Position Bottom Left",
    "Move Selection Down",
    "Close Small",
    "Upload 2",
    "Action Key",
    "Deployed Code Account",
    "Download 2",
    "Settings Heart",
    "Switch Access 2",
    "Collapse Content",
    "Highlight Keyboard Focus",
    "Highlight Text Cursor",
    "Person",
    "Person",
    "Group",
    "Share",
    "Thumb Up",
    "Groups",
    "Public",
    "Person Add",
    "Handshake",
    "Support Agent",
    "Face",
    "Sentiment Satisfied",
    "Rocket Launch",
    "Group Add",
    "Workspace Premium",
    "Psychology",
    "Diversity 3",
    "Emoji Objects",
    "Water Drop",
    "Eco",
    "Travel Explore",
    "Pets",
    "Mood",
    "Sunny",
    "Quiz",
    "Health And Safety",
    "Sentiment Dissatisfied",
    "Sentiment Very Satisfied",
    "Military Tech",
    "Thumb Down",
    "Gavel",
    "Recycling",
    "Diamond",
    "Monitor Heart",
    "Emoji People",
    "Diversity 1",
    "Workspaces",
    "Vaccines",
    "Compost",
    "Forest",
    "Recommend",
    "Waving Hand",
    "Person Remove",
    "Wc",
    "Sentiment Neutral",
    "Medication",
    "Sentiment Very Dissatisfied",
    "Group Work",
    "Diversity 2",
    "Front Hand",
    "Psychology Alt",
    "Cruelty Free",
    "Man",
    "Medical Information",
    "Coronavirus",
    "Add Reaction",
    "Rocket",
    "Female",
    "Potted Plant",
    "Emoji Nature",
    "Rainy",
    "Person Off",
    "Cookie",
    "Connect Without Contact",
    "Woman",
    "Mood Bad",
    "Male",
    "Bedtime",
    "Communication",
    "Groups 2",
    "Solar Power",
    "Thunderstorm",
    "Thumbs Up Down",
    "Partly Cloudy Day",
    "Emoji Flags",
    "Masks",
    "Hive",
    "Sentiment Extremely Dissatisfied",
    "Heart Broken",
    "Clear Day",
    "Boy",
    "Whatshot",
    "Cloudy Snowing",
    "Emoji Food Beverage",
    "Wind Power",
    "Emoji Transportation",
    "Elderly",
    "Face 6",
    "Reduce Capacity",
    "Sick",
    "Face 3",
    "Pregnant Woman",
    "Groups 3",
    "Bloodtype",
    "Skull",
    "Egg",
    "Group Remove",
    "Medication Liquid",
    "Co2",
    "Clear Night",
    "Weight",
    "Emoji Events",
    "Follow The Signs",
    "Face 4",
    "Elderly Woman",
    "Oil Barrel",
    "Transgender",
    "Sanitizer",
    "Clean Hands",
    "Person 2",
    "Bring Your Own Ip",
    "Public Off",
    "Face 2",
    "Routine",
    "Social Distance",
    "Sign Language",
    "South America",
    "Sunny Snowing",
    "Emoji Symbols",
    "Garden Cart",
    "Flood",
    "Face 5",
    "Egg Alt",
    "Cyclone",
    "Girl",
    "Person 4",
    "Dentistry",
    "Tsunami",
    "Group Off",
    "Outdoor Garden",
    "Partly Cloudy Night",
    "Severe Cold",
    "Snowing",
    "Person 3",
    "Tornado",
    "Safety Divider",
    "Landslide",
    "Vaping Rooms",
    "Foggy",
    "Woman 2",
    "No Adult Content",
    "Volcano",
    "6 Ft Apart",
    "Blind",
    "Man 2",
    "18 Up Rating",
    "Not Accessible",
    "Vape Free",
    "Man 4",
    "Partner Exchange",
    "Radiology",
    "Rib Cage",
    "Hand Bones",
    "Bedtime Off",
    "Rheumatology",
    "Man 3",
    "Orthopedics",
    "Tibia",
    "Skeleton",
    "Humerus",
    "Foot Bones",
    "Agender",
    "Communities",
    "Femur",
    "Tibia Alt",
    "Diversity 4",
    "Femur Alt",
    "Cognition",
    "Humerus Alt",
    "Ulna Radius",
    "Digital Wellbeing",
    "Ulna Radius Alt",
    "Specific Gravity",
    "Neurology",
    "Labs",
    "Eyeglasses",
    "Psychiatry",
    "Person Raised Hand",
    "Crowdsource",
    "Footprint",
    "Breastfeeding",
    "Vital Signs",
    "Globe",
    "Social Leaderboard",
    "Globe Asia",
    "Nutrition",
    "Demography",
    "Tactic",
    "Strategy",
    "Stethoscope",
    "Mystery",
    "Clinical Notes",
    "Sentiment Calm",
    "Sentiment Excited",
    "Taunt",
    "Conditions",
    "Sentiment Stressed",
    "Lab Research",
    "Globe Uk",
    "Pill",
    "Chess",
    "Crossword",
    "Genetics",
    "Sentiment Sad",
    "Folded Hands",
    "Home Health",
    "Wrist",
    "Altitude",
    "Not Accessible Forward",
    "Cardiology",
    "Domino Mask",
    "Falling",
    "Glucose",
    "Prescriptions",
    "Cookie Off",
    "Mountain Flag",
    "Person Alert",
    "Weather Hail",
    "Barefoot",
    "Deceased",
    "Microbiology",
    "Sentiment Content",
    "Weather Mix",
    "Cheer",
    "Person Check",
    "Emoticon",
    "Recent Patient",
    "Sentiment Frustrated",
    "Share Off",
    "Earthquake",
    "Mist",
    "Person Apron",
    "Prayer Times",
    "Sword Rose",
    "Water Bottle",
    "Helicopter",
    "Lab Panel",
    "Metabolism",
    "Playing Cards",
    "Dermatology",
    "Dew Point",
    "Sentiment Worried",
    "Bomb",
    "Ent",
    "Pulmonology",
    "Explosion",
    "Body System",
    "Raven",
    "Comic Bubble",
    "Infrared",
    "Oral Disease",
    "Oxygen Saturation",
    "Destruction",
    "Person Cancel",
    "Stethoscope Check",
    "Ward",
    "Water Lux",
    "Humidity Percentage",
    "Water Ph",
    "Allergies",
    "Blood Pressure",
    "Manga",
    "Stethoscope Arrow",
    "Water Voc",
    "Allergy",
    "Mixture Med",
    "Ophthalmology",
    "Outpatient",
    "Pediatrics",
    "Rainy Snow",
    "Water Do",
    "Body Fat",
    "Gastroenterology",
    "Gynecology",
    "Immunology",
    "Oncology",
    "Pregnancy",
    "Respiratory Rate",
    "Short Stay",
    "Snowing Heavy",
    "Symptoms",
    "Syringe",
    "Water Bottle Large",
    "Water Orp",
    "Wounds Injuries",
    "Admin Meds",
    "Editor Choice",
    "Endocrinology",
    "Fluid Balance",
    "Hematology",
    "Inpatient",
    "Moving Beds",
    "Nephrology",
    "Procedure",
    "Pulse Alert",
    "Rainy Light",
    "Salinity",
    "Candle",
    "Congenital",
    "Family Star",
    "Fluid",
    "Fluid Med",
    "Medical Mask",
    "Outpatient Med",
    "Rainy Heavy",
    "Surgical",
    "Total Dissolved Solids",
    "Urology",
    "Water Ec",
    "Kid Star",
    "Pill Off",
    "Account Circle",
    "Account Circle",
    "Info",
    "Visibility",
    "Calendar Month",
    "Schedule",
    "Help",
    "Warning",
    "Language",
    "Lock",
    "Error",
    "Visibility Off",
    "Verified",
    "Manage Accounts",
    "History",
    "Task Alt",
    "Event",
    "Bookmark",
    "Calendar Today",
    "Question Mark",
    "Lightbulb",
    "Fingerprint",
    "Category",
    "Update",
    "Lock Open",
    "Priority High",
    "Code",
    "Build",
    "Date Range",
    "Supervisor Account",
    "Upload File",
    "Event Available",
    "Ads Click",
    "Today",
    "Touch App",
    "Pending",
    "Preview",
    "Stars",
    "New Releases",
    "Celebration",
    "Account Box",
    "Bug Report",
    "Translate",
    "How To Reg",
    "Push Pin",
    "Alarm",
    "Edit Calendar",
    "Edit Square",
    "Label",
    "Extension",
    "Event Note",
    "Record Voice Over",
    "Rate Review",
    "Web",
    "Hourglass Empty",
    "Published With Changes",
    "Support",
    "Notification Important",
    "Accessibility New",
    "Help Center",
    "Bookmarks",
    "Pan Tool Alt",
    "Dangerous",
    "Supervised User Circle",
    "Interests",
    "Collections Bookmark",
    "All Inclusive",
    "Rule",
    "Priority",
    "Change History",
    "Event Upcoming",
    "Build Circle",
    "Api",
    "Wysiwyg",
    "Pan Tool",
    "Hotel Class",
    "Circle Notifications",
    "Manage History",
    "Web Asset",
    "Accessible",
    "Upgrade",
    "Input",
    "Bookmark Add",
    "Lock Reset",
    "Event Busy",
    "Model Training",
    "More Time",
    "Flutter Dash",
    "Save As",
    "Backup",
    "Dynamic Feed",
    "Accessibility",
    "Alarm On",
    "Pageview",
    "Home App Logo",
    "Label Important",
    "Perm Contact Calendar",
    "Approval",
    "Square Foot",
    "History Toggle Off",
    "More",
    "Swipe",
    "Component Exchange",
    "Event Repeat",
    "Bookmark Added",
    "App Shortcut",
    "Unpublished",
    "Open In Browser",
    "Notification Add",
    "Offline Bolt",
    "No Accounts",
    "Free Cancellation",
    "Background Replace",
    "Running With Errors",
    "Webhook",
    "Anchor",
    "3d Rotation",
    "Lock Person",
    "New Label",
    "Lock Clock",
    "Accessible Forward",
    "Auto Delete",
    "Add Alert",
    "Domain Verification",
    "Outbound",
    "Hand Gesture",
    "Tab",
    "Chrome Reader Mode",
    "Settings Power",
    "Gesture",
    "Online Prediction",
    "Lightbulb Circle",
    "Edit Notifications",
    "Find Replace",
    "Offline Pin",
    "Backup Table",
    "Ad Units",
    "Wifi Protected Setup",
    "Http",
    "Bookmark Remove",
    "Alarm Add",
    "Pinch Zoom Out",
    "On Device Training",
    "Snooze",
    "Batch Prediction",
    "Code Off",
    "Target",
    "Pinch Zoom In",
    "Feedback",
    "Commit",
    "Hourglass Disabled",
    "Settings Overscan",
    "Polymer",
    "Youtube Activity",
    "Logo Dev",
    "Time Auto",
    "Voice Over Off",
    "Alarm Off",
    "Person Add Disabled",
    "Update Disabled",
    "Timer 10 Alt 1",
    "Manufacturing",
    "Rounded Corner",
    "Label Off",
    "Timer 3 Alt 1",
    "All Out",
    "Tab Unselected",
    "Rsvp",
    "Web Asset Off",
    "Pin Invoke",
    "Web Traffic",
    "Pin End",
    "Code Blocks",
    "Arrow Selector Tool",
    "Approval Delegation",
    "Contacts Product",
    "Developer Guide",
    "Flutter",
    "License",
    "Reminder",
    "Feature Search",
    "Lists",
    "Problem",
    "User Attributes",
    "Browse",
    "Sdk",
    "Visibility Lock",
    "Award Star",
    "Release Alert",
    "Data Loss Prevention",
    "Ad Group",
    "Select Window",
    "Pan Zoom",
    "Search Hands Free",
    "Ad",
    "Lock Open Right",
    "Settings Account Box",
    "Draft Orders",
    "Ad Group Off",
    "Account Child Invert",
    "Account Child",
    "Shadow",
    "Add Ad",
    "Gesture Select",
    "Circles Ext",
    "Hourglass",
    "Calendar Clock",
    "Bookmark Manager",
    "Watch Screentime",
    "Account Circle Off",
    "Shift",
    "Ad Off",
    "Select Window Off",
    "Indeterminate Question Box",
    "Unlicense",
    "Alarm Smart Wake",
    "Circles",
    "Water Lock",
    "Help Clinic",
    "Info I",
    "Scrollable Header",
    "Warning Off",
    "Supervised User Circle Off",
    "Preview Off",
    "Domain Verification Off",
    "Measuring Tape",
    "Shift Lock",
    "Delete History",
    "Shadow Add",
    "Shadow Minus",
    "Mail",
    "Mail",
    "Call",
    "Notifications",
    "Send",
    "Chat",
    "Link",
    "Forum",
    "Inventory 2",
    "Phone In Talk",
    "Chat Bubble",
    "Contact Support",
    "Notifications Active",
    "Alternate Email",
    "Sms",
    "Comment",
    "Power Settings New",
    "Hub",
    "Person Search",
    "Import Contacts",
    "Contacts",
    "Contact Mail",
    "Live Help",
    "Forward To Inbox",
    "Reviews",
    "Mark Email Unread",
    "Lan",
    "Hourglass Top",
    "Contact Phone",
    "Mode Comment",
    "Inbox",
    "Drafts",
    "Outgoing Mail",
    "Hourglass Bottom",
    "Mark Email Read",
    "Link Off",
    "Calendar Add On",
    "Add Comment",
    "Phone Enabled",
    "G Translate",
    "Speaker Notes",
    "Perm Phone Msg",
    "Co Present",
    "Notifications Off",
    "Call End",
    "Topic",
    "Cell Tower",
    "Mark Chat Unread",
    "Schedule Send",
    "Dialpad",
    "Call Made",
    "Satellite Alt",
    "Mark Unread Chat Alt",
    "Unarchive",
    "3p",
    "Cancel Presentation",
    "Mark As Unread",
    "Move To Inbox",
    "Attach Email",
    "Next Plan",
    "Phonelink Ring",
    "Unsubscribe",
    "Phone Callback",
    "Call Received",
    "Settings Phone",
    "Call Split",
    "Present To All",
    "Add Call",
    "Markunread Mailbox",
    "All Inbox",
    "Voice Chat",
    "Phone Forwarded",
    "Mail Lock",
    "Attribution",
    "Voicemail",
    "Duo",
    "Contact Emergency",
    "Mark Chat Read",
    "Upcoming",
    "Phone Disabled",
    "Swap Calls",
    "Outbox",
    "Phonelink Lock",
    "Spoke",
    "Picture In Picture Alt",
    "Cancel Schedule Send",
    "Ring Volume",
    "Notifications Paused",
    "Quickreply",
    "Phone Missed",
    "Comment Bank",
    "Chat Add On",
    "Send And Archive",
    "Phonelink Erase",
    "Picture In Picture",
    "Settings Bluetooth",
    "Comments Disabled",
    "Video Chat",
    "Score",
    "Pause Presentation",
    "Speaker Phone",
    "Cell Wifi",
    "Speaker Notes Off",
    "Auto Read Play",
    "Mms",
    "Call Merge",
    "Play For Work",
    "Call Missed Outgoing",
    "Call Missed",
    "Wifi Channel",
    "Calendar Apps Script",
    "Phone Paused",
    "RTT",
    "Auto Read Pause",
    "Phone Locked",
    "Wifi Calling",
    "Chat Apps Script",
    "Dialer Sip",
    "Nat",
    "Sip",
    "Phone Bluetooth Speaker",
    "E911 Avatar",
    "Inbox Customize",
    "Stacked Email",
    "Business Messages",
    "Tooltip",
    "For You",
    "Chat Error",
    "Notification Multiple",
    "Chat Paste Go",
    "Ods",
    "Picture In Picture Small",
    "Call Quality",
    "Picture In Picture Off",
    "Signal Cellular Add",
    "Call Log",
    "Outbox Alt",
    "Chat Info",
    "Odt",
    "Network Intelligence Update",
    "Phonelink Ring Off",
    "Network Intelligence History",
    "Stacked Inbox",
    "Wifi Add",
    "Picture In Picture Medium",
    "Wifi Proxy",
    "Network Manage",
    "Picture In Picture Center",
    "Picture In Picture Large",
    "Notifications Unread",
    "Picture In Picture Mobile",
    "Edit",
    "Edit",
    "Photo Camera",
    "Filter Alt",
    "Image",
    "Navigate Next",
    "Tune",
    "Timer",
    "Picture As Pdf",
    "Circle",
    "Palette",
    "Add A Photo",
    "Photo Library",
    "Navigate Before",
    "Auto Stories",
    "Add Photo Alternate",
    "Brush",
    "Imagesmode",
    "Nature",
    "Flash On",
    "Wb Sunny",
    "Camera",
    "Looks One",
    "Straighten",
    "Landscape",
    "Timelapse",
    "Slideshow",
    "Grid On",
    "Rotate Right",
    "Crop Square",
    "Crop Free",
    "Adjust",
    "Style",
    "Aspect Ratio",
    "Brightness 6",
    "Photo",
    "Nature People",
    "Filter Vintage",
    "Image Search",
    "Crop",
    "Blur On",
    "Center Focus Strong",
    "Contrast",
    "Compare",
    "Looks Two",
    "Rotate Left",
    "Colorize",
    "Flare",
    "Filter None",
    "Wb Incandescent",
    "Filter Drama",
    "Healing",
    "Wb Twilight",
    "Looks 3",
    "Brightness 5",
    "Invert Colors",
    "Animation",
    "Lens",
    "Opacity",
    "Incomplete Circle",
    "Broken Image",
    "Filter Center Focus",
    "Add To Photos",
    "Brightness 4",
    "Flash Off",
    "Flip",
    "Auto Awesome Motion",
    "Center Focus Weak",
    "Flip Camera Android",
    "Mic External On",
    "Grain",
    "Lens Blur",
    "No Photography",
    "Details",
    "Panorama",
    "Web Stories",
    "GIF Box",
    "Dehaze",
    "Flaky",
    "Exposure Plus 1",
    "Loupe",
    "Settings Brightness",
    "Auto Awesome Mosaic",
    "Looks 4",
    "Texture",
    "Filter 1",
    "Flip Camera iOS",
    "Timer Off",
    "Panorama Fish Eye",
    "Brightness 1",
    "View Compact",
    "Filter",
    "Control Point Duplicate",
    "Photo Camera Front",
    "Brightness 7",
    "Photo Album",
    "Transform",
    "View Comfy",
    "Linked Camera",
    "Crop 16 9",
    "Hide Image",
    "Looks",
    "Looks 5",
    "Exposure",
    "Filter Hdr",
    "Rotate 90 Degrees Ccw",
    "GIF",
    "Brightness 3",
    "Hdr Strong",
    "Leak Add",
    "Gradient",
    "Hdr Auto",
    "Crop 7 5",
    "Vrpano",
    "Crop Portrait",
    "Camera Roll",
    "Motion Photos Auto",
    "Blur Circular",
    "Rotate 90 Degrees Cw",
    "Photo Size Select Small",
    "Brightness 2",
    "Looks 6",
    "Shutter Speed",
    "Camera Front",
    "Flash Auto",
    "Filter 2",
    "Crop Landscape",
    "Filter Tilt Shift",
    "Deblur",
    "Monochrome Photos",
    "Night Sight Auto",
    "Motion Photos Paused",
    "Crop 5 4",
    "Filter 4",
    "Hdr Weak",
    "Filter 3",
    "Crop Rotate",
    "Crop 3 2",
    "Tonality",
    "Ev Shadow",
    "Switch Camera",
    "Fluorescent",
    "Photo Frame",
    "Exposure Zero",
    "Photo Size Select Large",
    "Macro Off",
    "Filter Frames",
    "Party Mode",
    "Raw On",
    "Motion Blur",
    "Exposure Plus 2",
    "Photo Camera Back",
    "Blur Linear",
    "Exposure Neg 1",
    "Filter B And W",
    "Motion Photos Off",
    "Wb Iridescent",
    "Face Retouching Off",
    "Switch Video",
    "Panorama Horizontal",
    "Filter 5",
    "Blur Medium",
    "Invert Colors Off",
    "Filter 7",
    "Burst Mode",
    "Panorama Photosphere",
    "Hdr On",
    "Grid Off",
    "Filter 9 Plus",
    "Timer 10",
    "Filter 8",
    "Blur Short",
    "Dirty Lens",
    "Filter 9",
    "Wb Shade",
    "No Flash",
    "Filter 6",
    "Image Aspect Ratio",
    "Trail Length",
    "Exposure Neg 2",
    "Vignette",
    "Timer 3",
    "Leak Remove",
    "Blur Off",
    "60fps Select",
    "Perm Camera Mic",
    "30fps Select",
    "Trail Length Medium",
    "Camera Rear",
    "Mic External Off",
    "Trail Length Short",
    "Panorama Vertical",
    "Night Sight Auto Off",
    "Autofps Select",
    "Panorama Wide Angle",
    "Hdr Enhanced Select",
    "Mp",
    "Hdr Off",
    "24mp",
    "Hdr On Select",
    "22mp",
    "10mp",
    "12mp",
    "Hdr Plus",
    "18mp",
    "Hdr Auto Select",
    "Raw Off",
    "Wb Auto",
    "9mp",
    "13mp",
    "Hevc",
    "20mp",
    "5mp",
    "7mp",
    "15mp",
    "Hdr Off Select",
    "16mp",
    "19mp",
    "2mp",
    "14mp",
    "23mp",
    "8mp",
    "3mp",
    "6mp",
    "11mp",
    "21mp",
    "4mp",
    "17mp",
    "Gallery Thumbnail",
    "Masked Transitions",
    "Motion Photos On",
    "Settings B Roll",
    "Vr180 Create2d",
    "Settings Photo Camera",
    "Photo Prints",
    "Settings Video Camera",
    "Planner Banner Ad Pt",
    "Settings Panorama",
    "Settings Timelapse",
    "Settings Night Sight",
    "Unknown 2",
    "Motion Mode",
    "Settings Motion Mode",
    "Settings Cinematic Blur",
    "Vr180 Create2d Off",
    "Filter Retrolux",
    "50mp",
    "Background Dot Large",
    "Background Grid Small",
    "High Res",
    "Photo Auto Merge",
    "Settings Slow Motion",
    "Shutter Speed Add",
    "Macro Auto",
    "Texture Add",
    "Background Dot Small",
    "Crop 9 16",
    "Ev Shadow Add",
    "High Density",
    "Low Density",
    "Shutter Speed Minus",
    "Texture Minus",
    "Transition Dissolve",
    "Transition Fade",
    "Contrast Rtl Off",
    "Ev Shadow Minus",
    "Hdr Plus Off",
    "Transition Slide",
    "Transition Chop",
    "Transition Push",
    "Shopping Cart",
    "Shopping Cart",
    "Payments",
    "Shopping Bag",
    "Monitoring",
    "Credit Card",
    "Receipt Long",
    "Attach Money",
    "Storefront",
    "Database",
    "Trending Up",
    "Sell",
    "Account Balance",
    "Work",
    "Paid",
    "Account Balance Wallet",
    "Analytics",
    "Query Stats",
    "Store",
    "Savings",
    "Monetization On",
    "Calculate",
    "Qr Code Scanner",
    "Bar Chart",
    "Account Tree",
    "Add Shopping Cart",
    "Receipt",
    "Redeem",
    "Currency Exchange",
    "Trending Flat",
    "Shopping Basket",
    "Qr Code 2",
    "Domain",
    "Precision Manufacturing",
    "Qr Code",
    "Leaderboard",
    "Corporate Fare",
    "Timeline",
    "Insert Chart",
    "Currency Rupee",
    "Wallet",
    "Show Chart",
    "Work History",
    "Euro",
    "Meeting Room",
    "Credit Score",
    "Barcode Scanner",
    "Pie Chart",
    "Loyalty",
    "Copyright",
    "Conversion Path",
    "Barcode",
    "Trending Down",
    "Track Changes",
    "Price Check",
    "Euro Symbol",
    "Schema",
    "Add Business",
    "Add Card",
    "Card Membership",
    "Currency Bitcoin",
    "Price Change",
    "Production Quantity Limits",
    "Donut Large",
    "Tenancy",
    "Data Exploration",
    "Bubble Chart",
    "Donut Small",
    "Contactless",
    "Money",
    "Stacked Line Chart",
    "Stacked Bar Chart",
    "Toll",
    "Money Off",
    "Cases",
    "Currency Yen",
    "Currency Pound",
    "Area Chart",
    "Atr",
    "Remove Shopping Cart",
    "Room Preferences",
    "Add Chart",
    "Shop",
    "Domain Add",
    "Grouped Bar Chart",
    "Card Travel",
    "Legend Toggle",
    "Scatter Plot",
    "Credit Card Off",
    "Mediation",
    "Ssid Chart",
    "Candlestick Chart",
    "Waterfall Chart",
    "Full Stacked Bar Chart",
    "Currency Ruble",
    "Domain Disabled",
    "Shop Two",
    "Strikethrough S",
    "Atm",
    "Next Week",
    "Multiline Chart",
    "Currency Lira",
    "Currency Yuan",
    "No Meeting Room",
    "Troubleshoot",
    "Shoppingmode",
    "Currency Franc",
    "Finance Mode",
    "Data Table",
    "Source Environment",
    "Finance",
    "Bar Chart 4 Bars",
    "Orders",
    "Bid Landscape",
    "Enterprise",
    "Contactless Off",
    "Chart Data",
    "Podium",
    "Conveyor Belt",
    "Universal Currency Alt",
    "Planner Review",
    "Family History",
    "Flowsheet",
    "Order Approve",
    "Quick Reorder",
    "Energy",
    "Network Node",
    "Checkbook",
    "Universal Currency",
    "Send Money",
    "Box",
    "Mintmark",
    "Forklift",
    "Inactive Order",
    "Qr Code 2 Add",
    "Box Add",
    "Front Loader",
    "Pallet",
    "Mitre",
    "Enterprise Off",
    "Trolley",
    "Bid Landscape Disabled",
    "Barcode Reader",
    "Work Update",
    "Work Alert",
    "Conversion Path Off",
    "Order Play",
    "Box Edit",
    "Credit Card Heart",
    "Credit Card Gear",
    "Pin Drop",
    "Pin Drop",
    "Location On",
    "Map",
    "Home Pin",
    "Explore",
    "Restaurant",
    "Flag",
    "My Location",
    "Local Fire Department",
    "Person Pin Circle",
    "Local Mall",
    "Near Me",
    "Where To Vote",
    "Business Center",
    "East",
    "Restaurant Menu",
    "Handyman",
    "Factory",
    "Local Library",
    "Home Work",
    "Medical Services",
    "Layers",
    "Local Activity",
    "Share Location",
    "Emergency",
    "North East",
    "Add Location",
    "Fastfood",
    "Navigation",
    "Warehouse",
    "Person Pin",
    "Local Parking",
    "Home Repair Service",
    "Local Hospital",
    "Local Police",
    "South",
    "Zoom Out Map",
    "Location Searching",
    "Local Florist",
    "Location Away",
    "Crisis Alert",
    "West",
    "Local Gas Station",
    "Park",
    "Maps Ugc",
    "Cleaning Services",
    "Local Atm",
    "360",
    "Package",
    "Electrical Services",
    "Flag Circle",
    "North",
    "Add Location Alt",
    "Directions",
    "Fmd Bad",
    "Theater Comedy",
    "Local Drink",
    "Location Home",
    "Local Pizza",
    "Not Listed Location",
    "Local Post Office",
    "Wine Bar",
    "Beenhere",
    "Signpost",
    "Local Convenience Store",
    "Alt Route",
    "Tour",
    "Traffic",
    "Trip Origin",
    "Church",
    "Local Laundry Service",
    "Safety Check",
    "Ev Station",
    "Takeout Dining",
    "Moving",
    "Zoom In Map",
    "Soup Kitchen",
    "Pest Control",
    "Stadium",
    "Transfer Within A Station",
    "Location Off",
    "Connecting Airports",
    "Wrong Location",
    "Multiple Stop",
    "Edit Location",
    "Plumbing",
    "Mode Of Travel",
    "Minor Crash",
    "South East",
    "Local Pharmacy",
    "Add Road",
    "Fire Truck",
    "Castle",
    "Dry Cleaning",
    "Set Meal",
    "Baby Changing Station",
    "Edit Location Alt",
    "Layers Clear",
    "North West",
    "Mosque",
    "Edit Attributes",
    "Local Car Wash",
    "Run Circle",
    "Transit Enterexit",
    "Sos",
    "Satellite",
    "Edit Road",
    "South West",
    "Streetview",
    "Add Home",
    "Kebab Dining",
    "Airline Stops",
    "Fire Hydrant",
    "Local See",
    "Assist Walker",
    "Add Home Work",
    "Flight Class",
    "Remove Road",
    "No Meals",
    "Synagogue",
    "Fort",
    "Temple Buddhist",
    "Location Disabled",
    "Compass Calibration",
    "Temple Hindu",
    "Explore Off",
    "Pest Control Rodent",
    "Directions Alt",
    "Near Me Disabled",
    "Pergola",
    "Directions Off",
    "Things To Do",
    "Pet Supplies",
    "Directions Alt Off",
    "Explore Nearby",
    "Package 2",
    "Universal Local",
    "File Map",
    "Moved Location",
    "Move Location",
    "Safety Check Off",
    "Moving Ministry",
    "Move",
    "Description",
    "Description",
    "Content Copy",
    "Dashboard",
    "Edit Note",
    "Menu Book",
    "Grid View",
    "List",
    "Folder",
    "List Alt",
    "Inventory",
    "Folder Open",
    "Article",
    "Fact Check",
    "Attach File",
    "Format List Bulleted",
    "Assignment",
    "Task",
    "Checklist",
    "Cloud Upload",
    "Draft",
    "Summarize",
    "Cloud",
    "Draw",
    "Feed",
    "Newspaper",
    "View List",
    "File Copy",
    "Note Add",
    "Border Color",
    "Book",
    "History Edu",
    "Design Services",
    "Pending Actions",
    "Format Quote",
    "Post Add",
    "Request Quote",
    "Cloud Download",
    "Drag Handle",
    "Table",
    "Contact Page",
    "Archive",
    "Space Dashboard",
    "Content Paste",
    "Percent",
    "Attachment",
    "Assignment Ind",
    "Format List Numbered",
    "Assignment Turned In",
    "Tag",
    "Table Chart",
    "Dashboard Customize",
    "Sticky Note 2",
    "Text Fields",
    "Reorder",
    "Format Bold",
    "Integration Instructions",
    "Find In Page",
    "Text Snippet",
    "Note",
    "Document Scanner",
    "Checklist Rtl",
    "Note Alt",
    "Edit Document",
    "Cloud Sync",
    "Table Rows",
    "Perm Media",
    "Cloud Done",
    "Title",
    "Table View",
    "Content Cut",
    "Data Object",
    "Notes",
    "Cut",
    "Subject",
    "Functions",
    "Format Italic",
    "Content Paste Search",
    "Folder Shared",
    "Format Color Fill",
    "Plagiarism",
    "Horizontal Rule",
    "File Present",
    "Folder Copy",
    "Cloud Off",
    "Format Paint",
    "Ballot",
    "Team Dashboard",
    "Format Align Left",
    "Add Link",
    "View Column",
    "Difference",
    "Read More",
    "View Agenda",
    "Format Size",
    "Format Underlined",
    "Toc",
    "Vertical Align Top",
    "Height",
    "Vertical Align Bottom",
    "View Week",
    "Copy All",
    "Drive Folder Upload",
    "Assignment Late",
    "Format Color Text",
    "Drive File Move",
    "Low Priority",
    "View Module",
    "Assignment Return",
    "Folder Special",
    "Segment",
    "Format Align Center",
    "Calendar View Month",
    "Folder Zip",
    "Square",
    "Breaking News Alt 1",
    "Polyline",
    "Format Align Right",
    "Grading",
    "View Headline",
    "Linear Scale",
    "Edit Off",
    "View Quilt",
    "View Carousel",
    "Text Increase",
    "Request Page",
    "View Sidebar",
    "Text Format",
    "Pages",
    "Format Align Justify",
    "Calendar View Week",
    "Numbers",
    "Hexagon",
    "Docs Add On",
    "Folder Delete",
    "Forms Add On",
    "Format Shapes",
    "Imagesearch Roller",
    "Calendar View Day",
    "Video File",
    "Font Download",
    "Format List Numbered Rtl",
    "Add To Drive",
    "Join Inner",
    "Content Paste Go",
    "Restore Page",
    "Rectangle",
    "Format Color Reset",
    "Vertical Split",
    "Rule Folder",
    "View Stream",
    "Cloud Circle",
    "Format Indent Increase",
    "Spellcheck",
    "Data Array",
    "Assignment Returned",
    "Align Horizontal Left",
    "Pivot Table Chart",
    "Text Decrease",
    "Deselect",
    "Pentagon",
    "Vertical Align Center",
    "Space Bar",
    "Merge Type",
    "Format Strikethrough",
    "Short Text",
    "View Day",
    "Flip To Front",
    "Join Left",
    "Border All",
    "Shape Line",
    "Format Line Spacing",
    "Line Weight",
    "Horizontal Split",
    "Format Indent Decrease",
    "Join Right",
    "Align Horizontal Center",
    "Subtitles Off",
    "Snippet Folder",
    "Align Vertical Bottom",
    "Folder Off",
    "Glyphs",
    "Format Clear",
    "Align Horizontal Right",
    "Function",
    "Vertical Distribute",
    "Insert Page Break",
    "Content Paste Off",
    "Line Axis",
    "Horizontal Distribute",
    "Superscript",
    "Line Style",
    "Flip To Back",
    "Align Vertical Center",
    "Align Vertical Top",
    "Counter 1",
    "Margin",
    "Clarify",
    "Wrap Text",
    "Subscript",
    "View Array",
    "Ink Pen",
    "Border Style",
    "Border Clear",
    "Amp Stories",
    "Border Outer",
    "Ink Eraser",
    "Type Specimen",
    "Newsmode",
    "Text Rotate Vertical",
    "Padding",
    "Forms Apps Script",
    "Border Vertical",
    "Text Rotation None",
    "Format Textdirection L To R",
    "Docs Apps Script",
    "Ink Highlighter",
    "Format Overline",
    "Border Horizontal",
    "Font Download Off",
    "Format Textdirection R To L",
    "Finance Chip",
    "News",
    "Text Rotation Angleup",
    "Border Bottom",
    "Text Rotation Down",
    "Border Inner",
    "Border Left",
    "Border Top",
    "Assignment Add",
    "Text Rotation Angledown",
    "Equal",
    "Text Rotate Up",
    "Border Right",
    "Format H1",
    "Note Stack Add",
    "Join",
    "Frame Inspect",
    "View Column 2",
    "Counter 2",
    "Note Stack",
    "Overview",
    "Full Coverage",
    "Colors",
    "Signature",
    "Export Notes",
    "Slide Library",
    "Breaking News",
    "Format Underlined Squiggle",
    "Counter 3",
    "Lab Profile",
    "Format H2",
    "Format List Bulleted Add",
    "Format Paragraph",
    "Variables",
    "Format Image Left",
    "Csv",
    "File Save",
    "Rubric",
    "Reset Image",
    "Width",
    "Ink Marker",
    "Format Image Right",
    "Format Ink Highlighter",
    "Draw Abstract",
    "Remove Selection",
    "Format H3",
    "Text Fields Alt",
    "Process Chart",
    "Counter 4",
    "Shapes",
    "Contract",
    "Format H5",
    "Format H6",
    "Unknown Document",
    "Voting Chip",
    "Contract Edit",
    "Scan Delete",
    "Select",
    "Dictionary",
    "Diagnosis",
    "Add Notes",
    "Format H4",
    "Location Chip",
    "Stylus Laser Pointer",
    "Frame Source",
    "Sticky Note",
    "Article Shortcut",
    "Grid Guides",
    "Tab Duplicate",
    "Folder Managed",
    "Regular Expression",
    "Table Chart View",
    "Text Ad",
    "Cell Merge",
    "Lasso Select",
    "List Alt Add",
    "Smb Share",
    "Stock Media",
    "Table Rows Narrow",
    "Counter 5",
    "Business Chip",
    "Format Letter Spacing Standard",
    "Source Notes",
    "Text Select Move Forward Character",
    "Ungroup",
    "Format Text Overflow",
    "Line End Circle",
    "Book 2",
    "Custom Typography",
    "Decimal Increase",
    "Insert Text",
    "Match Case",
    "Scan",
    "Tab Group",
    "Line End Arrow",
    "Counter 6",
    "Folder Supervised",
    "Line End",
    "Line Start",
    "Thumbnail Bar",
    "Format Letter Spacing",
    "Format Letter Spacing 2",
    "Ink Highlighter Move",
    "Line Curve",
    "Line End Arrow Notch",
    "Tab Close",
    "Draw Collage",
    "Stroke Full",
    "Contract Delete",
    "Other Admission",
    "Text Select Start",
    "Top Panel Close",
    "Counter 0",
    "Counter 7",
    "Counter 8",
    "Counter 9",
    "Highlighter Size 3",
    "Line End Square",
    "Stroke Partial",
    "Text Select Jump To Beginning",
    "Flex Wrap",
    "Heap Snapshot Thumbnail",
    "Language Chinese Quick",
    "Language Spanish",
    "Line End Diamond",
    "Line Start Diamond",
    "Post",
    "Format Letter Spacing Wide",
    "Format Letter Spacing Wider",
    "Heap Snapshot Multiple",
    "Line Start Circle",
    "Match Word",
    "Person Book",
    "Attach File Add",
    "File Save Off",
    "Fit Width",
    "Flex Direction",
    "Heap Snapshot Large",
    "Ink Eraser Off",
    "Line Start Arrow",
    "Markdown Copy",
    "Special Character",
    "Tab Move",
    "Top Panel Open",
    "Tsv",
    "Align Justify Space Around",
    "Align Justify Space Between",
    "Align Space Between",
    "Book 5",
    "Format Text Clip",
    "Frame Reload",
    "Language French",
    "Language International",
    "Language Korean Latin",
    "Pen Size 5",
    "Tab New Right",
    "Text Select Jump To End",
    "Text Select Move Forward Word",
    "Align Justify Space Even",
    "Book 3",
    "Folder Data",
    "Language Gb English",
    "Line Start Square",
    "Pageless",
    "Pen Size 2",
    "Sheets Rtl",
    "Tab Close Right",
    "Tab Recent",
    "Text Select Move Back Word",
    "Text Select Move Up",
    "Two Pager",
    "Align Center",
    "Align Flex Center",
    "Decimal Decrease",
    "Fit Page",
    "Highlighter Size 5",
    "Language Chinese Dayi",
    "Language Chinese Wubi",
    "Language Pinyin",
    "Letter Switch",
    "Line Start Arrow Notch",
    "Pen Size 3",
    "Text Select Move Down",
    "Align Flex Start",
    "Align Justify Center",
    "Align Justify Flex End",
    "Align Justify Flex Start",
    "Align Self Stretch",
    "Align Space Around",
    "Align Space Even",
    "Asterisk",
    "Format Text Wrap",
    "Highlighter Size 4",
    "Language Chinese Array",
    "Language Chinese Cangjie",
    "Language Chinese Pinyin",
    "Language Us",
    "Language Us Colemak",
    "Language Us Dvorak",
    "Markdown",
    "Pen Size 4",
    "Text Select End",
    "Text Select Move Back Character",
    "Variable Add",
    "Align End",
    "Align Flex End",
    "Align Items Stretch",
    "Align Justify Stretch",
    "Align Start",
    "Align Stretch",
    "Book 4",
    "Flex No Wrap",
    "Highlighter Size 1",
    "Highlighter Size 2",
    "Language Japanese Kana",
    "Markdown Paste",
    "Pen Size 1",
    "Variable Insert",
    "Variable Remove",
    "Play Arrow",
    "Play Arrow",
    "Play Circle",
    "Mic",
    "Videocam",
    "Volume Up",
    "Pause",
    "Music Note",
    "Library Books",
    "Movie",
    "Speed",
    "Skip Next",
    "Replay",
    "Volume Off",
    "Pause Circle",
    "View In Ar",
    "Fiber Manual Record",
    "Skip Previous",
    "Stop Circle",
    "Stop",
    "Equalizer",
    "Subscriptions",
    "Video Library",
    "Fast Forward",
    "Playlist Add",
    "Video Call",
    "Repeat",
    "Volume Mute",
    "Shuffle",
    "Mic Off",
    "Hearing",
    "Library Music",
    "Playlist Add Check",
    "Podcasts",
    "Fast Rewind",
    "Queue Music",
    "Sound Detection Dog Barking",
    "Video Camera Front",
    "Subtitles",
    "Volume Down",
    "Play Pause",
    "Album",
    "Radio",
    "Discover Tune",
    "Av Timer",
    "Library Add Check",
    "Closed Caption",
    "Videocam Off",
    "Stream",
    "Forward 10",
    "Not Started",
    "Replay 10",
    "Fiber New",
    "Playlist Play",
    "Branding Watermark",
    "Text To Speech",
    "Recent Actors",
    "Playlist Remove",
    "Interpreter Mode",
    "Slow Motion Video",
    "Frame Person",
    "Playlist Add Check Circle",
    "Settings Voice",
    "Video Settings",
    "Featured Play List",
    "Sound Detection Loud Sound",
    "Audio File",
    "Lyrics",
    "Play Lesson",
    "Hd",
    "Repeat One",
    "Call To Action",
    "High Quality",
    "Add To Queue",
    "Music Off",
    "Video Camera Back",
    "Spatial Audio Off",
    "Shuffle On",
    "Playlist Add Circle",
    "Volume Down Alt",
    "Hearing Disabled",
    "Featured Video",
    "Replay 5",
    "Repeat On",
    "Queue Play Next",
    "Speech To Text",
    "Spatial Audio",
    "Art Track",
    "Explicit",
    "Airplay",
    "4k",
    "Forward 30",
    "Forward 5",
    "Music Video",
    "Replay 30",
    "Spatial Tracking",
    "Control Camera",
    "Closed Caption Disabled",
    "Digital Out Of Home",
    "Brand Awareness",
    "Video Label",
    "Fiber Smart Record",
    "Play Disabled",
    "Repeat One On",
    "Broadcast On Personal",
    "Sd",
    "Missed Video Call",
    "Surround Sound",
    "Fiber Pin",
    "10k",
    "60fps",
    "Sound Detection Glass Break",
    "Remove From Queue",
    "Broadcast On Home",
    "Fiber Dvr",
    "30fps",
    "4k Plus",
    "Video Stable",
    "8k",
    "1k",
    "Privacy",
    "Instant Mix",
    "8k Plus",
    "2k",
    "7k",
    "1k Plus",
    "9k Plus",
    "9k",
    "5k",
    "6k",
    "2k Plus",
    "5k Plus",
    "6k Plus",
    "3k",
    "3k Plus",
    "7k Plus",
    "Voice Selection",
    "Ar On You",
    "Music Cast",
    "No Sound",
    "Video Search",
    "Genres",
    "Hangout Video",
    "Cinematic Blur",
    "Media Link",
    "Video Camera Front Off",
    "Autoplay",
    "Movie Edit",
    "Artist",
    "Mic Double",
    "Autopause",
    "Forward Media",
    "Resume",
    "Ar Stickers",
    "Movie Info",
    "Select To Speak",
    "Audio Description",
    "Full Hd",
    "2d",
    "Hangout Video Off",
    "Autostop",
    "Forward Circle",
    "Frame Person Off",
    "Sound Sampler",
    "View In Ar Off",
    "Local Shipping",
    "Local Shipping",
    "Directions Car",
    "Flight",
    "Directions Run",
    "Directions Walk",
    "Flight Takeoff",
    "Directions Bus",
    "Train",
    "Directions Bike",
    "Airport Shuttle",
    "Pedal Bike",
    "Directions Boat",
    "Two Wheeler",
    "Agriculture",
    "Local Taxi",
    "Sailing",
    "Electric Car",
    "Flight Land",
    "Hail",
    "No Crash",
    "Commute",
    "Motorcycle",
    "Car Crash",
    "Tram",
    "Departure Board",
    "Subway",
    "Electric Moped",
    "Turn Right",
    "Electric Scooter",
    "Fork Right",
    "Directions Subway",
    "Tire Repair",
    "Electric Bike",
    "Rv Hookup",
    "Bus Alert",
    "Turn Left",
    "Transportation",
    "Airlines",
    "Taxi Alert",
    "U Turn Left",
    "Directions Railway",
    "Electric Rickshaw",
    "Turn Slight Right",
    "U Turn Right",
    "Fork Left",
    "Railway Alert",
    "Bike Scooter",
    "Turn Sharp Right",
    "Turn Slight Left",
    "No Transfer",
    "Snowmobile",
    "Turn Sharp Left",
    "Flightsmode",
    "Swap Driving Apps Wheel",
    "Swap Driving Apps",
    "Auto Towing",
    "Ambulance",
    "Auto Transmission",
    "School",
    "School",
    "Campaign",
    "Construction",
    "Engineering",
    "Volunteer Activism",
    "Science",
    "Sports Esports",
    "Confirmation Number",
    "Real Estate Agent",
    "Cake",
    "Self Improvement",
    "Sports Soccer",
    "Air",
    "Biotech",
    "Water",
    "Hiking",
    "Architecture",
    "Sports Score",
    "Personal Injury",
    "Sports Basketball",
    "Waves",
    "Theaters",
    "Sports Tennis",
    "Switch Account",
    "Nights Stay",
    "Sports Gymnastics",
    "How To Vote",
    "Backpack",
    "Sports Motorsports",
    "Surfing",
    "Sports Kabaddi",
    "Piano",
    "Experiment",
    "Sports",
    "Toys",
    "Sports Volleyball",
    "Camping",
    "Sports Baseball",
    "Sports Martial Arts",
    "Swords",
    "Downhill Skiing",
    "Scoreboard",
    "Kayaking",
    "Phishing",
    "Sports Handball",
    "Sports Football",
    "Skateboarding",
    "Trophy",
    "Sports Golf",
    "Toys Fan",
    "Sports Cricket",
    "Nordic Walking",
    "Roller Skating",
    "Kitesurfing",
    "Rowing",
    "Scuba Diving",
    "Storm",
    "Sports Mma",
    "Paragliding",
    "Featured Seasonal And Gifts",
    "Snowboarding",
    "Sports Hockey",
    "Ice Skating",
    "Snowshoeing",
    "Sports Rugby",
    "Sledding",
    "Family Link",
    "Piano Off",
    "No Backpack",
    "Rewarded Ads",
    "Ifl",
    "Steps",
    "Sprint",
    "Ecg Heart",
    "Health Metrics",
    "Toys And Games",
    "Mindfulness",
    "Cake Add",
    "Readiness Score",
    "Service Toolbox",
    "Exercise",
    "Stress Management",
    "Laps",
    "Sports And Outdoors",
    "Person Celebrate",
    "Person Play",
    "Floor",
    "Newsstand",
    "Menstrual Health",
    "Azm",
    "Relax",
    "Distance",
    "Pace",
    "Avg Pace",
    "Bath Private",
    "Play Shapes",
    "Water Medium",
    "Avg Time",
    "Interactive Space",
    "Water Full",
    "Bath Outdoor",
    "Onsen",
    "Eda",
    "Fertile",
    "Spo2",
    "Podiatry",
    "Elevation",
    "Bia",
    "Cleaning",
    "Glass Cup",
    "Hr Resting",
    "Bath Public Large",
    "Science Off",
    "Water Loss",
    "Check In Out",
    "Monitor Weight Loss",
    "Sauna",
    "Monitor Weight Gain",
    "Physical Therapy",
    "Sleep Score",
    "Phone iPhone",
    "Phone iPhone",
    "Save",
    "Smartphone",
    "Print",
    "Keyboard Arrow Down",
    "Computer",
    "Devices",
    "Desktop Windows",
    "Smart Display",
    "Dns",
    "Keyboard Backspace",
    "Headphones",
    "Smart Toy",
    "Phone Android",
    "Memory",
    "Keyboard Arrow Right",
    "Keyboard",
    "Live Tv",
    "Laptop Mac",
    "Tv",
    "Headset Mic",
    "Keyboard Arrow Up",
    "Device Thermostat",
    "Mouse",
    "Balance",
    "Route",
    "Point Of Sale",
    "Keyboard Arrow Left",
    "Laptop Chromebook",
    "Keyboard Return",
    "Watch",
    "Power",
    "Laptop Windows",
    "Router",
    "Developer Board",
    "Display Settings",
    "Scale",
    "Book Online",
    "Cast",
    "Developer Mode",
    "Fax",
    "Videogame Asset",
    "Cast For Education",
    "Device Hub",
    "Straight",
    "Screen Search Desktop",
    "Mobile Friendly",
    "Desktop Mac",
    "Settings Input Antenna",
    "Settings Ethernet",
    "Monitor",
    "Devices Other",
    "Send To Mobile",
    "Important Devices",
    "Tablet Mac",
    "System Update",
    "Settings Remote",
    "Monitor Weight",
    "Screen Rotation",
    "Screen Share",
    "Keyboard Alt",
    "Settings Input Component",
    "Sim Card",
    "Speaker",
    "Merge",
    "Tablet",
    "Vibration",
    "Keyboard Tab",
    "Connected Tv",
    "Power Off",
    "Screenshot Monitor",
    "Remember Me",
    "Browser Updated",
    "Security Update Good",
    "Sd Card",
    "Cast Connected",
    "Device Unknown",
    "Tablet Android",
    "Charging Station",
    "Phonelink Setup",
    "Punch Clock",
    "Screenshot",
    "Scanner",
    "Settings Input Hdmi",
    "Stay Current Portrait",
    "Tap And Play",
    "Keyboard Hide",
    "Print Disabled",
    "Security Update Warning",
    "Keyboard Capslock",
    "Speaker Group",
    "Disc Full",
    "App Blocking",
    "Mobile Screen Share",
    "Aod",
    "Sd Card Alert",
    "Tty",
    "Add To Home Screen",
    "Lift To Talk",
    "Earbuds",
    "Perm Device Information",
    "Stop Screen Share",
    "Mobile Off",
    "Headset Off",
    "Desktop Access Disabled",
    "Screen Lock Portrait",
    "Reset Tv",
    "Offline Share",
    "Adf Scanner",
    "Headphones Battery",
    "Dock",
    "Roundabout Right",
    "Settop Component",
    "Watch Off",
    "Settings Input Svideo",
    "Smart Screen",
    "Stay Current Landscape",
    "Chromecast Device",
    "Settings Cell",
    "Home Max",
    "Earbuds Battery",
    "Power Input",
    "No Sim",
    "Ramp Right",
    "Screen Lock Landscape",
    "Roundabout Left",
    "Stay Primary Portrait",
    "Stay Primary Landscape",
    "Developer Board Off",
    "Tv Off",
    "Home Mini",
    "Phonelink Off",
    "Open In Phone",
    "Ramp Left",
    "Screen Lock Rotation",
    "Videogame Asset Off",
    "Aod Tablet",
    "Gamepad",
    "Robot",
    "Devices Wearables",
    "Google Home Devices",
    "Robot 2",
    "Rear Camera",
    "Tv Options Edit Channels",
    "Jamboard Kiosk",
    "App Promo",
    "Developer Mode Tv",
    "Joystick",
    "Mimo",
    "Touchpad Mouse",
    "Memory Alt",
    "Mimo Disconnect",
    "Tv Options Input Settings",
    "Camera Video",
    "Tv Signin",
    "Devices Off",
    "Lightning Stand",
    "Aod Watch",
    "Hard Drive",
    "Tv Guide",
    "Ecg",
    "Night Sight Max",
    "General Device",
    "Missing Controller",
    "Assistant Device",
    "Reset Wrench",
    "Stream Apps",
    "Keyboard Tab Rtl",
    "Open Jam",
    "Cast Warning",
    "Deskphone",
    "Screenshot Tablet",
    "Cast Pause",
    "Hard Drive 2",
    "Pacemaker",
    "Tv Remote",
    "Watch Wake",
    "Audio Video Receiver",
    "Lda",
    "Print Connect",
    "Print Error",
    "P2p",
    "Print Add",
    "Print Lock",
    "Ventilator",
    "Watch Button Press",
    "Security Key",
    "Dark Mode",
    "Dark Mode",
    "Light Mode",
    "Wifi",
    "Signal Cellular Alt",
    "Password",
    "Widgets",
    "Android",
    "Storage",
    "Pin",
    "Rss Feed",
    "Battery Full",
    "Wifi Off",
    "Bluetooth",
    "Battery Charging Full",
    "Thermostat",
    "Dvr",
    "Graphic Eq",
    "Nightlight",
    "Battery 5 Bar",
    "Signal Wifi 4 Bar",
    "Gpp Maybe",
    "Cable",
    "Gpp Bad",
    "Data Usage",
    "Battery 4 Bar",
    "Signal Cellular 4 Bar",
    "Radar",
    "Battery Full Alt",
    "Airplanemode Active",
    "Cameraswitch",
    "Battery 0 Bar",
    "Wallpaper",
    "Flashlight On",
    "Signal Disconnected",
    "Network Check",
    "Battery 6 Bar",
    "Charger",
    "Wifi Tethering",
    "Sim Card Download",
    "Usb",
    "Quick Phrases",
    "Splitscreen",
    "ADB",
    "Battery 3 Bar",
    "Battery 1 Bar",
    "Network Wifi 3 Bar",
    "Battery Low",
    "Battery Alert",
    "Network Wifi",
    "Bluetooth Searching",
    "Bluetooth Connected",
    "Wifi Find",
    "5g",
    "Battery 2 Bar",
    "Brightness High",
    "Network Cell",
    "Nfc",
    "Pattern",
    "Data Saver On",
    "Bluetooth Disabled",
    "Signal Wifi Statusbar Not Connected",
    "Signal Wifi Bad",
    "Signal Cellular 3 Bar",
    "Network Wifi 2 Bar",
    "Network Wifi 1 Bar",
    "Noise Control Off",
    "Brightness Medium",
    "Signal Wifi Off",
    "Mode Standby",
    "Brightness Low",
    "Battery Very Low",
    "Mobiledata Off",
    "Signal Wifi 0 Bar",
    "Battery Charging 80",
    "Battery Charging 20",
    "Battery Saver",
    "Grid 4x4",
    "Battery Charging 90",
    "Flashlight Off",
    "Signal Wifi Statusbar Null",
    "Battery Charging 50",
    "Settings System Daydream",
    "Battery Unknown",
    "Signal Cellular 2 Bar",
    "Screen Rotation Alt",
    "Signal Cellular 1 Bar",
    "Wifi Calling 3",
    "Wifi Lock",
    "Badge Critical Battery",
    "4g Mobiledata",
    "Noise Aware",
    "Do Not Disturb On Total Silence",
    "Battery Charging 60",
    "Signal Cellular Connected No Internet 0 Bar",
    "Nearby Error",
    "Signal Cellular 0 Bar",
    "Battery Charging 30",
    "Network Ping",
    "Signal Cellular Connected No Internet 4 Bar",
    "Wifi Tethering Error",
    "Brightness Auto",
    "Edgesensor High",
    "Wifi Calling 1",
    "Signal Cellular Nodata",
    "Wifi 2 Bar",
    "Grid 3x3",
    "LTE Mobiledata",
    "1x Mobiledata",
    "Airplanemode Inactive",
    "Perm Data Setting",
    "Signal Cellular Alt 2 Bar",
    "Devices Fold",
    "Bluetooth Drive",
    "Perm Scan Wifi",
    "Network Locked",
    "4g Plus Mobiledata",
    "Media Bluetooth On",
    "Wifi Calling 2",
    "Signal Cellular Off",
    "Timer 10 Select",
    "Wifi Tethering Off",
    "Edgesensor Low",
    "Signal Cellular Alt 1 Bar",
    "Wifi 1 Bar",
    "3g Mobiledata",
    "Usb Off",
    "Apk Install",
    "Signal Cellular Null",
    "LTE Plus Mobiledata",
    "iOS",
    "Grid Goldenratio",
    "G Mobiledata",
    "Portable Wifi Off",
    "Noise Control On",
    "Media Bluetooth Off",
    "Timer 3 Select",
    "Apk Document",
    "E Mobiledata",
    "Nearby Off",
    "H Mobiledata",
    "R Mobiledata",
    "H Plus Mobiledata",
    "Dock To Left",
    "Dual Screen",
    "Stylus Note",
    "Bigtop Updates",
    "Stylus",
    "Nearby",
    "Overview Key",
    "Dock To Right",
    "Screenshot Region",
    "Brightness Alert",
    "Screenshot Frame",
    "Screen Record",
    "Brightness Empty",
    "Display External Input",
    "Network Wifi 3 Bar Locked",
    "Battery Status Good",
    "Keyboard Keys",
    "Splitscreen Right",
    "Splitscreen Left",
    "Screenshot Keyboard",
    "Keyboard External Input",
    "Magnify Docked",
    "Battery Error",
    "Screen Rotation Up",
    "Magnify Fullscreen",
    "Wallpaper Slideshow",
    "Dock To Bottom",
    "Keyboard Off",
    "Network Wifi 2 Bar Locked",
    "Network Wifi Locked",
    "Battery Plus",
    "Keyboard Capslock Badge",
    "Backlight Low",
    "Battery Change",
    "Network Wifi 1 Bar Locked",
    "1x Mobiledata Badge",
    "5g Mobiledata Badge",
    "Keyboard Full",
    "Wifi Home",
    "Wifi Notification",
    "Backlight High",
    "H Plus Mobiledata Badge",
    "Keyboard Onscreen",
    "Keyboard Previous Language",
    "LTE Mobiledata Badge",
    "Splitscreen Bottom",
    "Splitscreen Top",
    "3g Mobiledata Badge",
    "4g Mobiledata Badge",
    "E Mobiledata Badge",
    "G Mobiledata Badge",
    "Grid 3x3 Off",
    "H Mobiledata Badge",
    "LTE Plus Mobiledata Badge",
    "Battery Share",
    "Ev Mobiledata Badge",
    "Signal Cellular Pause",
    "Badge",
    "Badge",
    "Verified User",
    "Admin Panel Settings",
    "Report",
    "Security",
    "Vpn Key",
    "Shield",
    "Policy",
    "Exclamation",
    "Privacy Tip",
    "Assured Workload",
    "Vpn Lock",
    "Disabled Visible",
    "E911 Emergency",
    "Enhanced Encryption",
    "Private Connectivity",
    "Vpn Key Off",
    "Add Moderator",
    "Encrypted",
    "No Encryption",
    "Sync Lock",
    "Wifi Password",
    "Key Visualizer",
    "Remove Moderator",
    "Report Off",
    "Passkey",
    "Shield Lock",
    "Shield Person",
    "Shield Locked",
    "Vpn Key Alert",
    "Shield Question",
    "Apartment",
    "Apartment",
    "Location City",
    "Fitness Center",
    "Lunch Dining",
    "Spa",
    "Cottage",
    "Local Cafe",
    "Hotel",
    "Family Restroom",
    "Beach Access",
    "Local Bar",
    "Pool",
    "Other Houses",
    "Luggage",
    "Liquor",
    "Casino",
    "Airplane Ticket",
    "Room Service",
    "Sports Bar",
    "Bakery Dining",
    "Ramen Dining",
    "Nightlife",
    "Local Dining",
    "Holiday Village",
    "Icecream",
    "Escalator Warning",
    "Dinner Dining",
    "Museum",
    "Food Bank",
    "Night Shelter",
    "Festival",
    "Attractions",
    "Golf Course",
    "Stairs",
    "Villa",
    "Smoke Free",
    "Smoking Rooms",
    "Car Rental",
    "Airline Seat Recline Normal",
    "Elevator",
    "Gite",
    "Child Friendly",
    "Airline Seat Recline Extra",
    "Breakfast Dining",
    "Carpenter",
    "Car Repair",
    "Cabin",
    "Brunch Dining",
    "Do Not Touch",
    "No Food",
    "Houseboat",
    "Tapas",
    "Rice Bowl",
    "Wheelchair Pickup",
    "Bento",
    "No Drinks",
    "Do Not Step",
    "Airline Seat Flat",
    "Bungalow",
    "Escalator",
    "Airline Seat Individual Suite",
    "Chalet",
    "No Luggage",
    "Travel",
    "Airline Seat Legroom Extra",
    "Airline Seat Flat Angled",
    "Airline Seat Legroom Normal",
    "Airline Seat Legroom Reduced",
    "No Stroller",
    "Flights And Hotels",
    "Personal Places",
    "Trip",
    "Travel Luggage And Bags",
    "Personal Bag",
    "Checked Bag",
    "Concierge",
    "Personal Bag Question",
    "Carry On Bag Question",
    "Your Trips",
    "Checked Bag Question",
    "Carry On Bag Checked",
    "Carry On Bag",
    "Personal Bag Off",
    "Carry On Bag Inactive",
    "House",
    "House",
    "Bed",
    "Ac Unit",
    "Chair",
    "Electric Bolt",
    "Coffee",
    "Sensors",
    "Child Care",
    "Back Hand",
    "Emergency Home",
    "Checkroom",
    "Grass",
    "Shower",
    "Mode Fan",
    "Mop",
    "Kitchen",
    "Thermometer",
    "Styler",
    "Yard",
    "Bathtub",
    "King Bed",
    "Roofing",
    "Energy Savings Leaf",
    "Window",
    "Valve",
    "Cooking",
    "Garage Home",
    "Door Front",
    "Mode Heat",
    "Light",
    "Foundation",
    "Garage",
    "Outdoor Grill",
    "Table Restaurant",
    "Dining",
    "Sensor Occupied",
    "Deck",
    "Weekend",
    "Coffee Maker",
    "Humidity High",
    "Flatware",
    "Highlight",
    "Fireplace",
    "Humidity Low",
    "Mode Night",
    "Electric Meter",
    "Tv Gen",
    "Humidity Mid",
    "Bedroom Parent",
    "Chair Alt",
    "Blender",
    "Scene",
    "Microwave",
    "Heat Pump",
    "Bedroom Baby",
    "Single Bed",
    "Oven Gen",
    "Bathroom",
    "Hardware",
    "In Home Mode",
    "Hot Tub",
    "Mode Off On",
    "Sprinkler",
    "Table Bar",
    "Gas Meter",
    "Mode Cool",
    "Crib",
    "Propane Tank",
    "Soap",
    "Living",
    "Countertops",
    "Home Iot Device",
    "Fire Extinguisher",
    "Outlet",
    "Gate",
    "Remote Gen",
    "Matter",
    "Sensor Door",
    "Event Seat",
    "Airware",
    "Faucet",
    "Dishwasher Gen",
    "Air Freshener",
    "Energy Program Saving",
    "Balcony",
    "Water Damage",
    "Wash",
    "Camera Indoor",
    "Bedroom Child",
    "House Siding",
    "Switch",
    "Microwave Gen",
    "Detector Smoke",
    "Door Sliding",
    "Iron",
    "Energy Program Time Used",
    "Desk",
    "Umbrella",
    "Water Heater",
    "Fence",
    "Dresser",
    "Doorbell",
    "Door Back",
    "Mode Fan Off",
    "Hvac",
    "Emergency Share",
    "Kettle",
    "Camera Outdoor",
    "Air Purifier Gen",
    "Emergency Heat",
    "Stroller",
    "Curtains",
    "Multicooker",
    "Shield Moon",
    "Sensors Off",
    "Mode Heat Cool",
    "Emergency Recording",
    "Thermostat Auto",
    "Smart Outlet",
    "Controller Gen",
    "Blinds",
    "Roller Shades",
    "Dry",
    "Blinds Closed",
    "Roller Shades Closed",
    "Propane",
    "Sensor Window",
    "Apparel",
    "Thermostat Carbon",
    "Range Hood",
    "Tv With Assistant",
    "Doorbell 3p",
    "Blanket",
    "Vertical Shades Closed",
    "Vertical Shades",
    "Curtains Closed",
    "Mode Heat Off",
    "Mode Cool Off",
    "Family Home",
    "Health And Beauty",
    "Tamper Detection Off",
    "Grocery",
    "Light Off",
    "Shelves",
    "Household Supplies",
    "Vacuum",
    "Wall Art",
    "Garage Door",
    "Dishwasher",
    "Home And Garden",
    "Thermometer Add",
    "Thermometer Gain",
    "Air Purifier",
    "Home Improvement And Tools",
    "Oven",
    "Thermometer Loss",
    "Hallway",
    "Skillet",
    "Thermometer Minus",
    "Emergency Share Off",
    "Stockpot",
    "Skillet Cooktop",
    "Stadia Controller",
    "Stadia Controller",
    "Door Open",
    "Nest Eco Leaf",
    "Device Reset",
    "Nest Remote Comfort Sensor",
    "Nest Clock Farsight Analog",
    "Laundry",
    "Battery Horiz 075",
    "Shield With Heart",
    "Temp Preferences Eco",
    "Familiar Face And Zone",
    "Tools Power Drill",
    "Airwave",
    "Productivity",
    "Battery Horiz 050",
    "Nest Heat Link Gen 3",
    "Nest Display",
    "Weather Snowy",
    "Ev Charger",
    "Activity Zone",
    "Nest Remote",
    "Cleaning Bucket",
    "Settings Alert",
    "Nest Cam Indoor",
    "Arrows More Up",
    "Home Storage",
    "Nest Heat Link E",
    "Nest Multi Room",
    "Nest Secure Alarm",
    "Battery Horiz 000",
    "Light Group",
    "Nest Cam Outdoor",
    "Google Wifi",
    "Detection And Zone",
    "Nest Thermostat Gen 3",
    "Mfg Nest Yale Lock",
    "Tools Pliers Wire Stripper",
    "Detector Alarm",
    "Tools Ladder",
    "Early On",
    "Nest Cam Iq Outdoor",
    "Nest Mini",
    "Floor Lamp",
    "Nest Cam Iq",
    "Nest Clock Farsight Digital",
    "Home Speaker",
    "Nest Hello Doorbell",
    "Nest Audio",
    "Home Max Dots",
    "Motion Sensor Active",
    "Nest Wifi Router",
    "Cool To Dry",
    "House With Shield",
    "Zone Person Urgent",
    "Nest Display Max",
    "Nest Farsight Weather",
    "Shield With House",
    "Chromecast 2",
    "Battery Profile",
    "Heat Pump Balance",
    "Window Closed",
    "Arming Countdown",
    "Nest Found Savings",
    "Self Care",
    "Detector Status",
    "Window Open",
    "Tools Level",
    "Nest Thermostat Zirconium Eu",
    "Zone Person Alert",
    "Arrows More Down",
    "Nest True Radiant",
    "Detector",
    "Nest Cam Wired Stand",
    "Nest Detect",
    "Climate Mini Split",
    "Door Sensor",
    "Nest Wifi Point",
    "Nest Doorbell Visitor",
    "Nest Cam Floodlight",
    "Nest Tag",
    "Quiet Time",
    "Tools Installation Kit",
    "Nest Connect",
    "Nest Thermostat Sensor",
    "Nest Thermostat Sensor Eu",
    "Nest Sunblock",
    "Tools Phillips",
    "Doorbell Chime",
    "Nest Thermostat E Eu",
    "Detector Co",
    "Table Lamp",
    "Detector Battery",
    "Tools Flat Head",
    "Nest Wake On Approach",
    "Nest Wake On Press",
    "Motion Sensor Urgent",
    "Motion Sensor Alert",
    "Window Sensor",
    "Tamper Detection On",
    "Nest Cam Magnet Mount",
    "Zone Person Idle",
    "Quiet Time Active",
    "Nest Cam Stand",
    "Nest Cam Wall Mount",
    "Wall Lamp",
    "Detector Offline",
    "Motion Sensor Idle",
    "Water Pump",
    "Sensors Krx",
    "Nest Thermostat",
    "Heat",
    "Assistant On Hub",
    "Mode Dual",
    "Nest Protect",
    "Aq Indoor",
    "On Hub Device",
    "Google Tv Remote",
    "Aq",
    "Sensors Krx Off",
    "Nest Wifi Pro",
    "Nest Wifi Pro 2",
    "Farsight Digital",
    "Humidity Indoor",
    "Nest Gale Wifi",
    "Nest Gale Wifi"
].map(e => e.toLowerCase()).map(e => e.replace(" ", "_"))


const uniqueIcons = new Set(allIcons);

const content = [...uniqueIcons].map(e => `"${e}"`).join(',\n')

writeFileSync('./icon-names.schema', `
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "IconNames",
    "title": "Icon Names",
    "enum": [
        ${content}
    ]
}
`);