export type GoogleIcons =
  | 'search'
  | 'home'
  | 'menu'
  | 'close'
  | 'settings'
  | 'done'
  | 'expand_more'
  | 'check_circle'
  | 'favorite'
  | 'add'
  | 'delete'
  | 'arrow_back'
  | 'star'
  | 'chevron_right'
  | 'logout'
  | 'arrow_forward ios'
  | 'add_circle'
  | 'cancel'
  | 'arrow_back ios'
  | 'arrow_forward'
  | 'arrow_drop down'
  | 'more_vert'
  | 'check'
  | 'check_box'
  | 'toggle_on'
  | 'grade'
  | 'open_in new'
  | 'refresh'
  | 'check_box outline blank'
  | 'login'
  | 'chevron_left'
  | 'expand_less'
  | 'radio_button unchecked'
  | 'more_horiz'
  | 'apps'
  | 'download'
  | 'arrow_right alt'
  | 'radio_button checked'
  | 'remove'
  | 'bolt'
  | 'toggle_off'
  | 'arrow_upward'
  | 'filter_list'
  | 'delete_forever'
  | 'autorenew'
  | 'key'
  | 'sync'
  | 'arrow_downward'
  | 'block'
  | 'sort'
  | 'add_box'
  | 'arrow_back ios new'
  | 'restart_alt'
  | 'shopping_cart checkout'
  | 'menu_open'
  | 'expand_circle down'
  | 'backspace'
  | 'undo'
  | 'arrow_circle right'
  | 'done_all'
  | 'arrow_right'
  | 'do_not disturb on'
  | 'open_in full'
  | 'manage_search'
  | 'double_arrow'
  | 'sync_alt'
  | 'zoom_in'
  | 'done_outline'
  | 'drag_indicator'
  | 'fullscreen'
  | 'keyboard_double arrow right'
  | 'star_half'
  | 'settings_accessibility'
  | 'ios_share'
  | 'arrow_drop up'
  | 'reply'
  | 'exit_to app'
  | 'unfold_more'
  | 'library_add'
  | 'cached'
  | 'terminal'
  | 'select_check box'
  | 'change_circle'
  | 'disabled_by default'
  | 'swap_horiz'
  | 'swap_vert'
  | 'close_fullscreen'
  | 'app_registration'
  | 'download_for offline'
  | 'arrow_circle left'
  | 'arrow_circle up'
  | 'file_open'
  | 'minimize'
  | 'dataset'
  | 'open_with'
  | 'keyboard_double arrow left'
  | 'add_task'
  | 'start'
  | 'keyboard_voice'
  | 'keyboard_double arrow down'
  | 'create_new folder'
  | 'forward'
  | 'downloading'
  | 'settings_applications'
  | 'upload'
  | 'compare_arrows'
  | 'redo'
  | 'publish'
  | 'zoom_out'
  | 'arrow_left'
  | 'html'
  | 'token'
  | 'switch_access shortcut'
  | 'fullscreen_exit'
  | 'arrow_circle down'
  | 'sort_by alpha'
  | 'delete_sweep'
  | 'indeterminate_check box'
  | 'first_page'
  | 'view_timeline'
  | 'keyboard_double arrow up'
  | 'settings_backup restore'
  | 'arrow_drop down circle'
  | 'assistant_navigation'
  | 'sync_problem'
  | 'clear_all'
  | 'density_medium'
  | 'heart_plus'
  | 'expand'
  | 'filter_alt off'
  | 'last_page'
  | 'subdirectory_arrow right'
  | 'unfold_less'
  | 'arrow_outward'
  | 'download_done'
  | '123'
  | 'swipe_left'
  | 'saved_search'
  | 'system_update alt'
  | 'place_item'
  | 'search_off'
  | 'output'
  | 'maximize'
  | 'javascript'
  | 'swipe_up'
  | 'fit_screen'
  | 'select_all'
  | 'hide_source'
  | 'dynamic_form'
  | 'swipe_right'
  | 'check_small'
  | 'switch_access shortcut add'
  | 'browse_gallery'
  | 'density_small'
  | 'css'
  | 'assistant_direction'
  | 'file_download done'
  | 'move_up'
  | 'youtube_searched for'
  | 'swap_horizontal circle'
  | 'data_thresholding'
  | 'install_mobile'
  | 'abc'
  | 'dataset_linked'
  | 'move_down'
  | 'restore_from trash'
  | 'enable'
  | 'install_desktop'
  | 'keyboard_command key'
  | 'browse_activity'
  | 'view_kanban'
  | 'reply_all'
  | 'switch_left'
  | 'compress'
  | 'swipe_down'
  | 'swap_vertical circle'
  | 'remove_done'
  | 'apps_outage'
  | 'filter_list off'
  | 'star_rate'
  | 'hide'
  | 'switch_right'
  | 'swipe_vertical'
  | 'more_up'
  | 'sync_disabled'
  | 'pinch'
  | 'keyboard_control key'
  | 'eject'
  | 'key_off'
  | 'php'
  | 'subdirectory_arrow left'
  | 'view_cozy'
  | 'transcribe'
  | 'do_not disturb off'
  | 'send_time extension'
  | 'width_normal'
  | 'view_comfy alt'
  | 'heart_minus'
  | 'share_reviews'
  | 'width_full'
  | 'unfold_more double'
  | 'file_download off'
  | 'view_compact alt'
  | 'extension_off'
  | 'open_in new off'
  | 'check_indeterminate small'
  | 'more_down'
  | 'width_wide'
  | 'repartition'
  | 'density_large'
  | 'swipe_left alt'
  | 'swipe_down alt'
  | 'swipe_up alt'
  | 'swipe_right alt'
  | 'unfold_less double'
  | 'cycle'
  | 'progress_activity'
  | 'keyboard_option key'
  | 'hls'
  | 'hls_off'
  | 'file_upload off'
  | 'expand_content'
  | 'rebase'
  | 'expand_all'
  | 'collapse_all'
  | 'rebase_edit'
  | 'quick_reference all'
  | 'arrow_split'
  | 'deployed_code'
  | 'empty_dashboard'
  | 'stack'
  | 'stat_0'
  | 'acute'
  | 'arrow_upward alt'
  | 'switches'
  | 'left_click'
  | 'data_check'
  | 'arrow_downward alt'
  | 'directory_sync'
  | 'data_alert'
  | 'quick_reference'
  | 'page_info'
  | 'sync_saved locally'
  | 'cards'
  | 'side_navigation'
  | 'clock_loader 60'
  | 'data_info alert'
  | 'bubble'
  | 'question_exchange'
  | 'steppers'
  | 'move_item'
  | 'point_scan'
  | 'stack_star'
  | 'arrow_left alt'
  | 'preliminary'
  | 'stat_3'
  | 'captive_portal'
  | 'search_check'
  | 'star_rate half'
  | 'unknown_med'
  | 'toolbar'
  | 'right_panel close'
  | 'new_window'
  | 'clock_loader 10'
  | 'sweep'
  | 'right_panel open'
  | 'rule_settings'
  | 'responsive_layout'
  | 'step'
  | 'patient_list'
  | 'drag_pan'
  | 'clock_loader 40'
  | 'expand_circle right'
  | 'share_windows'
  | 'arrow_insert'
  | 'stat_minus 1'
  | 'left_panel close'
  | 'page_control'
  | 'dialogs'
  | 'expand_circle up'
  | 'input_circle'
  | 'heart_check'
  | 'move_group'
  | 'stat_2'
  | 'capture'
  | 'stat_minus 2'
  | 'left_panel open'
  | 'clock_loader 80'
  | 'step_into'
  | 'all_match'
  | 'bottom_panel open'
  | 'clock_loader 90'
  | 'resize'
  | 'stack_off'
  | 'stat_1'
  | 'magnification_small'
  | 'partner_reports'
  | 'radio_button partial'
  | 'deployed_code update'
  | 'dropdown'
  | 'magnification_large'
  | 'pip'
  | 'bottom_navigation'
  | 'event_list'
  | 'clock_loader 20'
  | 'sliders'
  | 'tabs'
  | 'bottom_drawer'
  | 'buttons_alt'
  | 'chronic'
  | 'drag_click'
  | 'go_to line'
  | 'right_click'
  | 'shelf_position'
  | 'stat_minus 3'
  | 'arrow_and edge'
  | 'bottom_sheets'
  | 'open_in new down'
  | 'step_over'
  | 'arrow_range'
  | 'chip_extraction'
  | 'iframe'
  | 'unknown_5'
  | 'linked_services'
  | 'ripples'
  | 'move_selection left'
  | 'toast'
  | 'reopen_window'
  | 'subheader'
  | 'arrow_or edge'
  | 'bottom_right click'
  | 'chips'
  | 'output_circle'
  | 'switch_access'
  | 'arrows_outward'
  | 'step_out'
  | 'app_badging'
  | 'arrow_top left'
  | 'back_to tab'
  | 'pip_exit'
  | 'error_med'
  | 'key_vertical'
  | 'amend'
  | 'deployed_code history'
  | 'jump_to element'
  | 'move_selection right'
  | 'move_selection up'
  | 'arrow_top right'
  | 'bubbles'
  | 'position_top right'
  | 'stacks'
  | 'deployed_code alert'
  | 'position_bottom right'
  | 'shelf_auto hide'
  | 'bottom_app bar'
  | 'bottom_panel close'
  | 'iframe_off'
  | 'highlight_mouse cursor'
  | 'position_bottom left'
  | 'move_selection down'
  | 'action_key'
  | 'close_small'
  | 'collapse_content'
  | 'settings_heart'
  | 'upload_2'
  | 'deployed_code account'
  | 'download_2'
  | 'switch_access 2'
  | 'highlight_keyboard focus'
  | 'highlight_text cursor'
  | 'person'
  | 'group'
  | 'share'
  | 'thumb_up'
  | 'groups'
  | 'public'
  | 'person_add'
  | 'handshake'
  | 'support_agent'
  | 'face'
  | 'sentiment_satisfied'
  | 'rocket_launch'
  | 'group_add'
  | 'workspace_premium'
  | 'psychology'
  | 'diversity_3'
  | 'emoji_objects'
  | 'water_drop'
  | 'eco'
  | 'travel_explore'
  | 'pets'
  | 'mood'
  | 'sunny'
  | 'quiz'
  | 'health_and safety'
  | 'sentiment_dissatisfied'
  | 'sentiment_very satisfied'
  | 'military_tech'
  | 'thumb_down'
  | 'gavel'
  | 'recycling'
  | 'diamond'
  | 'monitor_heart'
  | 'emoji_people'
  | 'diversity_1'
  | 'workspaces'
  | 'vaccines'
  | 'compost'
  | 'forest'
  | 'recommend'
  | 'waving_hand'
  | 'person_remove'
  | 'wc'
  | 'sentiment_neutral'
  | 'medication'
  | 'sentiment_very dissatisfied'
  | 'group_work'
  | 'diversity_2'
  | 'front_hand'
  | 'psychology_alt'
  | 'cruelty_free'
  | 'man'
  | 'medical_information'
  | 'coronavirus'
  | 'add_reaction'
  | 'rocket'
  | 'female'
  | 'potted_plant'
  | 'emoji_nature'
  | 'rainy'
  | 'person_off'
  | 'cookie'
  | 'connect_without contact'
  | 'woman'
  | 'mood_bad'
  | 'male'
  | 'bedtime'
  | 'communication'
  | 'groups_2'
  | 'solar_power'
  | 'thunderstorm'
  | 'thumbs_up down'
  | 'partly_cloudy day'
  | 'emoji_flags'
  | 'masks'
  | 'hive'
  | 'sentiment_extremely dissatisfied'
  | 'heart_broken'
  | 'clear_day'
  | 'boy'
  | 'whatshot'
  | 'cloudy_snowing'
  | 'emoji_food beverage'
  | 'wind_power'
  | 'emoji_transportation'
  | 'elderly'
  | 'face_6'
  | 'reduce_capacity'
  | 'sick'
  | 'face_3'
  | 'pregnant_woman'
  | 'groups_3'
  | 'bloodtype'
  | 'skull'
  | 'egg'
  | 'group_remove'
  | 'medication_liquid'
  | 'co2'
  | 'clear_night'
  | 'weight'
  | 'emoji_events'
  | 'follow_the signs'
  | 'face_4'
  | 'elderly_woman'
  | 'oil_barrel'
  | 'transgender'
  | 'sanitizer'
  | 'clean_hands'
  | 'person_2'
  | 'bring_your own ip'
  | 'public_off'
  | 'face_2'
  | 'routine'
  | 'social_distance'
  | 'sign_language'
  | 'south_america'
  | 'sunny_snowing'
  | 'emoji_symbols'
  | 'garden_cart'
  | 'flood'
  | 'face_5'
  | 'egg_alt'
  | 'cyclone'
  | 'girl'
  | 'person_4'
  | 'dentistry'
  | 'tsunami'
  | 'group_off'
  | 'outdoor_garden'
  | 'partly_cloudy night'
  | 'severe_cold'
  | 'snowing'
  | 'person_3'
  | 'tornado'
  | 'safety_divider'
  | 'vaping_rooms'
  | 'landslide'
  | 'foggy'
  | 'woman_2'
  | 'no_adult content'
  | 'volcano'
  | '6_ft apart'
  | 'blind'
  | 'man_2'
  | '18_up rating'
  | 'not_accessible'
  | 'vape_free'
  | 'man_4'
  | 'partner_exchange'
  | 'radiology'
  | 'rib_cage'
  | 'hand_bones'
  | 'bedtime_off'
  | 'rheumatology'
  | 'man_3'
  | 'orthopedics'
  | 'tibia'
  | 'skeleton'
  | 'humerus'
  | 'foot_bones'
  | 'agender'
  | 'communities'
  | 'femur'
  | 'tibia_alt'
  | 'diversity_4'
  | 'femur_alt'
  | 'cognition'
  | 'humerus_alt'
  | 'ulna_radius'
  | 'digital_wellbeing'
  | 'ulna_radius alt'
  | 'specific_gravity'
  | 'neurology'
  | 'labs'
  | 'psychiatry'
  | 'eyeglasses'
  | 'person_raised hand'
  | 'crowdsource'
  | 'footprint'
  | 'breastfeeding'
  | 'vital_signs'
  | 'globe'
  | 'social_leaderboard'
  | 'globe_asia'
  | 'nutrition'
  | 'demography'
  | 'tactic'
  | 'strategy'
  | 'stethoscope'
  | 'mystery'
  | 'clinical_notes'
  | 'sentiment_calm'
  | 'sentiment_excited'
  | 'taunt'
  | 'conditions'
  | 'sentiment_stressed'
  | 'lab_research'
  | 'globe_uk'
  | 'pill'
  | 'chess'
  | 'crossword'
  | 'genetics'
  | 'sentiment_sad'
  | 'folded_hands'
  | 'home_health'
  | 'wrist'
  | 'altitude'
  | 'not_accessible forward'
  | 'cardiology'
  | 'cookie_off'
  | 'deceased'
  | 'domino_mask'
  | 'falling'
  | 'glucose'
  | 'prescriptions'
  | 'mountain_flag'
  | 'person_alert'
  | 'weather_hail'
  | 'barefoot'
  | 'microbiology'
  | 'weather_mix'
  | 'cheer'
  | 'sentiment_content'
  | 'earthquake'
  | 'person_check'
  | 'emoticon'
  | 'recent_patient'
  | 'sentiment_frustrated'
  | 'share_off'
  | 'mist'
  | 'person_apron'
  | 'prayer_times'
  | 'sword_rose'
  | 'water_bottle'
  | 'helicopter'
  | 'lab_panel'
  | 'metabolism'
  | 'playing_cards'
  | 'dermatology'
  | 'dew_point'
  | 'sentiment_worried'
  | 'bomb'
  | 'ent'
  | 'pulmonology'
  | 'explosion'
  | 'body_system'
  | 'raven'
  | 'comic_bubble'
  | 'infrared'
  | 'oral_disease'
  | 'oxygen_saturation'
  | 'destruction'
  | 'person_cancel'
  | 'stethoscope_check'
  | 'ward'
  | 'water_lux'
  | 'humidity_percentage'
  | 'water_ph'
  | 'allergies'
  | 'blood_pressure'
  | 'manga'
  | 'stethoscope_arrow'
  | 'water_voc'
  | 'allergy'
  | 'mixture_med'
  | 'ophthalmology'
  | 'outpatient'
  | 'pediatrics'
  | 'rainy_snow'
  | 'water_do'
  | 'body_fat'
  | 'editor_choice'
  | 'gastroenterology'
  | 'gynecology'
  | 'immunology'
  | 'oncology'
  | 'pregnancy'
  | 'respiratory_rate'
  | 'short_stay'
  | 'snowing_heavy'
  | 'symptoms'
  | 'syringe'
  | 'water_bottle large'
  | 'water_orp'
  | 'wounds_injuries'
  | 'admin_meds'
  | 'endocrinology'
  | 'fluid_balance'
  | 'hematology'
  | 'inpatient'
  | 'moving_beds'
  | 'nephrology'
  | 'procedure'
  | 'pulse_alert'
  | 'rainy_light'
  | 'salinity'
  | 'candle'
  | 'congenital'
  | 'family_star'
  | 'fluid'
  | 'fluid_med'
  | 'medical_mask'
  | 'outpatient_med'
  | 'rainy_heavy'
  | 'surgical'
  | 'total_dissolved solids'
  | 'urology'
  | 'water_ec'
  | 'kid_star'
  | 'pill_off'
  | 'account_circle'
  | 'info'
  | 'visibility'
  | 'calendar_month'
  | 'schedule'
  | 'help'
  | 'warning'
  | 'language'
  | 'lock'
  | 'error'
  | 'visibility_off'
  | 'verified'
  | 'manage_accounts'
  | 'history'
  | 'task_alt'
  | 'event'
  | 'bookmark'
  | 'calendar_today'
  | 'question_mark'
  | 'lightbulb'
  | 'fingerprint'
  | 'category'
  | 'update'
  | 'lock_open'
  | 'priority_high'
  | 'code'
  | 'build'
  | 'date_range'
  | 'supervisor_account'
  | 'upload_file'
  | 'event_available'
  | 'ads_click'
  | 'today'
  | 'touch_app'
  | 'pending'
  | 'preview'
  | 'stars'
  | 'new_releases'
  | 'celebration'
  | 'bug_report'
  | 'account_box'
  | 'translate'
  | 'how_to reg'
  | 'push_pin'
  | 'alarm'
  | 'edit_calendar'
  | 'edit_square'
  | 'label'
  | 'extension'
  | 'event_note'
  | 'record_voice over'
  | 'rate_review'
  | 'web'
  | 'hourglass_empty'
  | 'published_with changes'
  | 'support'
  | 'notification_important'
  | 'accessibility_new'
  | 'help_center'
  | 'bookmarks'
  | 'pan_tool alt'
  | 'dangerous'
  | 'supervised_user circle'
  | 'interests'
  | 'collections_bookmark'
  | 'all_inclusive'
  | 'rule'
  | 'priority'
  | 'change_history'
  | 'event_upcoming'
  | 'build_circle'
  | 'api'
  | 'wysiwyg'
  | 'pan_tool'
  | 'hotel_class'
  | 'circle_notifications'
  | 'manage_history'
  | 'web_asset'
  | 'accessible'
  | 'upgrade'
  | 'input'
  | 'bookmark_add'
  | 'lock_reset'
  | 'event_busy'
  | 'model_training'
  | 'more_time'
  | 'flutter_dash'
  | 'save_as'
  | 'backup'
  | 'dynamic_feed'
  | 'accessibility'
  | 'alarm_on'
  | 'pageview'
  | 'home_app logo'
  | 'label_important'
  | 'perm_contact calendar'
  | 'approval'
  | 'square_foot'
  | 'history_toggle off'
  | 'more'
  | 'swipe'
  | 'component_exchange'
  | 'event_repeat'
  | 'bookmark_added'
  | 'app_shortcut'
  | 'unpublished'
  | 'open_in browser'
  | 'notification_add'
  | 'offline_bolt'
  | 'no_accounts'
  | 'free_cancellation'
  | 'background_replace'
  | 'running_with errors'
  | 'webhook'
  | 'anchor'
  | '3d_rotation'
  | 'lock_person'
  | 'new_label'
  | 'lock_clock'
  | 'accessible_forward'
  | 'auto_delete'
  | 'add_alert'
  | 'domain_verification'
  | 'outbound'
  | 'hand_gesture'
  | 'tab'
  | 'chrome_reader mode'
  | 'gesture'
  | 'settings_power'
  | 'online_prediction'
  | 'lightbulb_circle'
  | 'edit_notifications'
  | 'find_replace'
  | 'offline_pin'
  | 'backup_table'
  | 'ad_units'
  | 'wifi_protected setup'
  | 'http'
  | 'bookmark_remove'
  | 'alarm_add'
  | 'pinch_zoom out'
  | 'on_device training'
  | 'snooze'
  | 'batch_prediction'
  | 'code_off'
  | 'target'
  | 'feedback'
  | 'pinch_zoom in'
  | 'commit'
  | 'hourglass_disabled'
  | 'settings_overscan'
  | 'polymer'
  | 'youtube_activity'
  | 'logo_dev'
  | 'time_auto'
  | 'voice_over off'
  | 'alarm_off'
  | 'person_add disabled'
  | 'update_disabled'
  | 'timer_10 alt 1'
  | 'manufacturing'
  | 'rounded_corner'
  | 'label_off'
  | 'timer_3 alt 1'
  | 'all_out'
  | 'tab_unselected'
  | 'rsvp'
  | 'web_asset off'
  | 'pin_invoke'
  | 'web_traffic'
  | 'pin_end'
  | 'code_blocks'
  | 'arrow_selector tool'
  | 'approval_delegation'
  | 'contacts_product'
  | 'developer_guide'
  | 'flutter'
  | 'license'
  | 'reminder'
  | 'feature_search'
  | 'lists'
  | 'problem'
  | 'user_attributes'
  | 'browse'
  | 'sdk'
  | 'visibility_lock'
  | 'award_star'
  | 'release_alert'
  | 'data_loss prevention'
  | 'ad_group'
  | 'select_window'
  | 'settings_account box'
  | 'pan_zoom'
  | 'lock_open right'
  | 'search_hands free'
  | 'ad'
  | 'draft_orders'
  | 'ad_group off'
  | 'account_child invert'
  | 'account_child'
  | 'shadow'
  | 'add_ad'
  | 'gesture_select'
  | 'circles_ext'
  | 'hourglass'
  | 'calendar_clock'
  | 'bookmark_manager'
  | 'watch_screentime'
  | 'account_circle off'
  | 'shift'
  | 'ad_off'
  | 'indeterminate_question box'
  | 'select_window off'
  | 'info_i'
  | 'unlicense'
  | 'alarm_smart wake'
  | 'circles'
  | 'water_lock'
  | 'help_clinic'
  | 'scrollable_header'
  | 'warning_off'
  | 'supervised_user circle off'
  | 'preview_off'
  | 'domain_verification off'
  | 'measuring_tape'
  | 'shift_lock'
  | 'delete_history'
  | 'shadow_add'
  | 'shadow_minus'
  | 'mail'
  | 'call'
  | 'notifications'
  | 'send'
  | 'chat'
  | 'link'
  | 'forum'
  | 'inventory_2'
  | 'phone_in talk'
  | 'chat_bubble'
  | 'contact_support'
  | 'notifications_active'
  | 'alternate_email'
  | 'sms'
  | 'comment'
  | 'power_settings new'
  | 'hub'
  | 'person_search'
  | 'import_contacts'
  | 'contacts'
  | 'contact_mail'
  | 'live_help'
  | 'forward_to inbox'
  | 'reviews'
  | 'mark_email unread'
  | 'lan'
  | 'hourglass_top'
  | 'contact_phone'
  | 'mode_comment'
  | 'inbox'
  | 'drafts'
  | 'outgoing_mail'
  | 'hourglass_bottom'
  | 'mark_email read'
  | 'link_off'
  | 'calendar_add on'
  | 'add_comment'
  | 'phone_enabled'
  | 'g_translate'
  | 'speaker_notes'
  | 'perm_phone msg'
  | 'co_present'
  | 'notifications_off'
  | 'call_end'
  | 'topic'
  | 'cell_tower'
  | 'mark_chat unread'
  | 'schedule_send'
  | 'dialpad'
  | 'call_made'
  | 'satellite_alt'
  | 'mark_unread chat alt'
  | 'unarchive'
  | '3p'
  | 'cancel_presentation'
  | 'mark_as unread'
  | 'move_to inbox'
  | 'attach_email'
  | 'next_plan'
  | 'phonelink_ring'
  | 'unsubscribe'
  | 'phone_callback'
  | 'call_received'
  | 'settings_phone'
  | 'call_split'
  | 'present_to all'
  | 'add_call'
  | 'markunread_mailbox'
  | 'all_inbox'
  | 'voice_chat'
  | 'phone_forwarded'
  | 'mail_lock'
  | 'attribution'
  | 'voicemail'
  | 'duo'
  | 'contact_emergency'
  | 'mark_chat read'
  | 'upcoming'
  | 'phone_disabled'
  | 'swap_calls'
  | 'outbox'
  | 'phonelink_lock'
  | 'spoke'
  | 'picture_in picture alt'
  | 'cancel_schedule send'
  | 'ring_volume'
  | 'notifications_paused'
  | 'quickreply'
  | 'phone_missed'
  | 'comment_bank'
  | 'chat_add on'
  | 'send_and archive'
  | 'picture_in picture'
  | 'phonelink_erase'
  | 'settings_bluetooth'
  | 'comments_disabled'
  | 'video_chat'
  | 'score'
  | 'pause_presentation'
  | 'speaker_phone'
  | 'cell_wifi'
  | 'speaker_notes off'
  | 'auto_read play'
  | 'mms'
  | 'call_merge'
  | 'play_for work'
  | 'call_missed outgoing'
  | 'call_missed'
  | 'wifi_channel'
  | 'calendar_apps script'
  | 'phone_paused'
  | 'rtt'
  | 'auto_read pause'
  | 'phone_locked'
  | 'wifi_calling'
  | 'chat_apps script'
  | 'dialer_sip'
  | 'nat'
  | 'sip'
  | 'phone_bluetooth speaker'
  | 'e911_avatar'
  | 'inbox_customize'
  | 'stacked_email'
  | 'business_messages'
  | 'tooltip'
  | 'for_you'
  | 'chat_error'
  | 'notification_multiple'
  | 'chat_paste go'
  | 'ods'
  | 'picture_in picture small'
  | 'call_quality'
  | 'picture_in picture off'
  | 'signal_cellular add'
  | 'call_log'
  | 'chat_info'
  | 'outbox_alt'
  | 'odt'
  | 'network_intelligence update'
  | 'phonelink_ring off'
  | 'network_intelligence history'
  | 'stacked_inbox'
  | 'wifi_add'
  | 'picture_in picture medium'
  | 'wifi_proxy'
  | 'network_manage'
  | 'picture_in picture center'
  | 'picture_in picture large'
  | 'notifications_unread'
  | 'picture_in picture mobile'
  | 'edit'
  | 'photo_camera'
  | 'filter_alt'
  | 'image'
  | 'navigate_next'
  | 'tune'
  | 'timer'
  | 'picture_as pdf'
  | 'circle'
  | 'palette'
  | 'add_a photo'
  | 'photo_library'
  | 'navigate_before'
  | 'auto_stories'
  | 'add_photo alternate'
  | 'brush'
  | 'imagesmode'
  | 'nature'
  | 'flash_on'
  | 'wb_sunny'
  | 'camera'
  | 'looks_one'
  | 'straighten'
  | 'landscape'
  | 'timelapse'
  | 'slideshow'
  | 'grid_on'
  | 'rotate_right'
  | 'crop_square'
  | 'crop_free'
  | 'adjust'
  | 'style'
  | 'aspect_ratio'
  | 'brightness_6'
  | 'photo'
  | 'nature_people'
  | 'filter_vintage'
  | 'image_search'
  | 'crop'
  | 'blur_on'
  | 'center_focus strong'
  | 'contrast'
  | 'compare'
  | 'looks_two'
  | 'rotate_left'
  | 'colorize'
  | 'flare'
  | 'filter_none'
  | 'wb_incandescent'
  | 'filter_drama'
  | 'healing'
  | 'wb_twilight'
  | 'looks_3'
  | 'brightness_5'
  | 'invert_colors'
  | 'animation'
  | 'lens'
  | 'opacity'
  | 'incomplete_circle'
  | 'broken_image'
  | 'filter_center focus'
  | 'add_to photos'
  | 'brightness_4'
  | 'flash_off'
  | 'flip'
  | 'auto_awesome motion'
  | 'center_focus weak'
  | 'flip_camera android'
  | 'mic_external on'
  | 'grain'
  | 'lens_blur'
  | 'no_photography'
  | 'details'
  | 'panorama'
  | 'web_stories'
  | 'gif_box'
  | 'dehaze'
  | 'flaky'
  | 'exposure_plus 1'
  | 'loupe'
  | 'settings_brightness'
  | 'auto_awesome mosaic'
  | 'looks_4'
  | 'texture'
  | 'filter_1'
  | 'flip_camera ios'
  | 'timer_off'
  | 'panorama_fish eye'
  | 'brightness_1'
  | 'filter'
  | 'view_compact'
  | 'control_point duplicate'
  | 'photo_camera front'
  | 'brightness_7'
  | 'transform'
  | 'photo_album'
  | 'view_comfy'
  | 'linked_camera'
  | 'crop_16 9'
  | 'hide_image'
  | 'looks'
  | 'looks_5'
  | 'exposure'
  | 'rotate_90 degrees ccw'
  | 'filter_hdr'
  | 'gif'
  | 'brightness_3'
  | 'hdr_strong'
  | 'leak_add'
  | 'gradient'
  | 'hdr_auto'
  | 'crop_7 5'
  | 'vrpano'
  | 'crop_portrait'
  | 'camera_roll'
  | 'motion_photos auto'
  | 'blur_circular'
  | 'rotate_90 degrees cw'
  | 'photo_size select small'
  | 'brightness_2'
  | 'looks_6'
  | 'shutter_speed'
  | 'camera_front'
  | 'flash_auto'
  | 'filter_2'
  | 'crop_landscape'
  | 'filter_tilt shift'
  | 'deblur'
  | 'monochrome_photos'
  | 'night_sight auto'
  | 'motion_photos paused'
  | 'crop_5 4'
  | 'filter_4'
  | 'hdr_weak'
  | 'filter_3'
  | 'crop_rotate'
  | 'tonality'
  | 'crop_3 2'
  | 'ev_shadow'
  | 'fluorescent'
  | 'switch_camera'
  | 'photo_frame'
  | 'exposure_zero'
  | 'photo_size select large'
  | 'macro_off'
  | 'filter_frames'
  | 'party_mode'
  | 'raw_on'
  | 'motion_blur'
  | 'exposure_plus 2'
  | 'photo_camera back'
  | 'blur_linear'
  | 'exposure_neg 1'
  | 'filter_b and w'
  | 'motion_photos off'
  | 'wb_iridescent'
  | 'face_retouching off'
  | 'switch_video'
  | 'panorama_horizontal'
  | 'filter_5'
  | 'blur_medium'
  | 'invert_colors off'
  | 'filter_7'
  | 'burst_mode'
  | 'panorama_photosphere'
  | 'hdr_on'
  | 'grid_off'
  | 'filter_9 plus'
  | 'timer_10'
  | 'filter_8'
  | 'blur_short'
  | 'dirty_lens'
  | 'filter_9'
  | 'wb_shade'
  | 'no_flash'
  | 'filter_6'
  | 'image_aspect ratio'
  | 'trail_length'
  | 'exposure_neg 2'
  | 'vignette'
  | 'timer_3'
  | 'leak_remove'
  | 'blur_off'
  | '60fps_select'
  | 'perm_camera mic'
  | '30fps_select'
  | 'trail_length medium'
  | 'camera_rear'
  | 'mic_external off'
  | 'trail_length short'
  | 'panorama_vertical'
  | 'night_sight auto off'
  | 'autofps_select'
  | 'panorama_wide angle'
  | 'hdr_enhanced select'
  | 'mp'
  | 'hdr_off'
  | '24mp'
  | 'hdr_on select'
  | '22mp'
  | '10mp'
  | '12mp'
  | 'hdr_plus'
  | '18mp'
  | 'hdr_auto select'
  | 'raw_off'
  | 'wb_auto'
  | '9mp'
  | '13mp'
  | 'hevc'
  | '20mp'
  | '5mp'
  | '7mp'
  | '15mp'
  | 'hdr_off select'
  | '16mp'
  | '19mp'
  | '2mp'
  | '14mp'
  | '23mp'
  | '8mp'
  | '3mp'
  | '6mp'
  | '11mp'
  | '21mp'
  | '4mp'
  | '17mp'
  | 'gallery_thumbnail'
  | 'masked_transitions'
  | 'motion_photos on'
  | 'settings_b roll'
  | 'vr180_create2d'
  | 'settings_photo camera'
  | 'photo_prints'
  | 'settings_video camera'
  | 'planner_banner ad pt'
  | 'settings_panorama'
  | 'settings_timelapse'
  | 'settings_night sight'
  | 'unknown_2'
  | 'settings_motion mode'
  | 'motion_mode'
  | 'settings_cinematic blur'
  | 'vr180_create2d off'
  | 'filter_retrolux'
  | '50mp'
  | 'background_dot large'
  | 'background_grid small'
  | 'high_res'
  | 'photo_auto merge'
  | 'settings_slow motion'
  | 'shutter_speed add'
  | 'macro_auto'
  | 'texture_add'
  | 'crop_9 16'
  | 'transition_fade'
  | 'background_dot small'
  | 'ev_shadow add'
  | 'high_density'
  | 'low_density'
  | 'shutter_speed minus'
  | 'texture_minus'
  | 'transition_dissolve'
  | 'contrast_rtl off'
  | 'ev_shadow minus'
  | 'hdr_plus off'
  | 'transition_slide'
  | 'transition_chop'
  | 'transition_push'
  | 'shopping_cart'
  | 'payments'
  | 'shopping_bag'
  | 'monitoring'
  | 'credit_card'
  | 'receipt_long'
  | 'attach_money'
  | 'storefront'
  | 'database'
  | 'trending_up'
  | 'sell'
  | 'account_balance'
  | 'work'
  | 'paid'
  | 'account_balance wallet'
  | 'analytics'
  | 'query_stats'
  | 'store'
  | 'savings'
  | 'monetization_on'
  | 'calculate'
  | 'qr_code scanner'
  | 'bar_chart'
  | 'account_tree'
  | 'add_shopping cart'
  | 'receipt'
  | 'redeem'
  | 'currency_exchange'
  | 'trending_flat'
  | 'shopping_basket'
  | 'qr_code 2'
  | 'domain'
  | 'precision_manufacturing'
  | 'qr_code'
  | 'leaderboard'
  | 'corporate_fare'
  | 'timeline'
  | 'insert_chart'
  | 'currency_rupee'
  | 'wallet'
  | 'show_chart'
  | 'work_history'
  | 'euro'
  | 'meeting_room'
  | 'credit_score'
  | 'barcode_scanner'
  | 'pie_chart'
  | 'loyalty'
  | 'copyright'
  | 'conversion_path'
  | 'barcode'
  | 'trending_down'
  | 'track_changes'
  | 'price_check'
  | 'euro_symbol'
  | 'schema'
  | 'add_business'
  | 'add_card'
  | 'card_membership'
  | 'currency_bitcoin'
  | 'price_change'
  | 'production_quantity limits'
  | 'donut_large'
  | 'tenancy'
  | 'data_exploration'
  | 'bubble_chart'
  | 'donut_small'
  | 'contactless'
  | 'money'
  | 'stacked_line chart'
  | 'stacked_bar chart'
  | 'toll'
  | 'money_off'
  | 'cases'
  | 'currency_yen'
  | 'currency_pound'
  | 'area_chart'
  | 'atr'
  | 'remove_shopping cart'
  | 'room_preferences'
  | 'add_chart'
  | 'shop'
  | 'domain_add'
  | 'grouped_bar chart'
  | 'card_travel'
  | 'legend_toggle'
  | 'scatter_plot'
  | 'credit_card off'
  | 'mediation'
  | 'ssid_chart'
  | 'candlestick_chart'
  | 'waterfall_chart'
  | 'full_stacked bar chart'
  | 'currency_ruble'
  | 'domain_disabled'
  | 'shop_two'
  | 'strikethrough_s'
  | 'atm'
  | 'next_week'
  | 'multiline_chart'
  | 'currency_lira'
  | 'currency_yuan'
  | 'no_meeting room'
  | 'troubleshoot'
  | 'shoppingmode'
  | 'currency_franc'
  | 'finance_mode'
  | 'data_table'
  | 'source_environment'
  | 'finance'
  | 'bar_chart 4 bars'
  | 'orders'
  | 'bid_landscape'
  | 'enterprise'
  | 'contactless_off'
  | 'chart_data'
  | 'podium'
  | 'conveyor_belt'
  | 'universal_currency alt'
  | 'planner_review'
  | 'family_history'
  | 'flowsheet'
  | 'order_approve'
  | 'quick_reorder'
  | 'energy'
  | 'network_node'
  | 'checkbook'
  | 'universal_currency'
  | 'send_money'
  | 'box'
  | 'mintmark'
  | 'forklift'
  | 'inactive_order'
  | 'qr_code 2 add'
  | 'box_add'
  | 'front_loader'
  | 'pallet'
  | 'mitre'
  | 'enterprise_off'
  | 'trolley'
  | 'bid_landscape disabled'
  | 'barcode_reader'
  | 'work_update'
  | 'conversion_path off'
  | 'order_play'
  | 'work_alert'
  | 'box_edit'
  | 'credit_card heart'
  | 'credit_card gear'
  | 'pin_drop'
  | 'location_on'
  | 'map'
  | 'home_pin'
  | 'explore'
  | 'restaurant'
  | 'flag'
  | 'my_location'
  | 'local_fire department'
  | 'person_pin circle'
  | 'local_mall'
  | 'near_me'
  | 'where_to vote'
  | 'business_center'
  | 'east'
  | 'restaurant_menu'
  | 'handyman'
  | 'factory'
  | 'local_library'
  | 'home_work'
  | 'medical_services'
  | 'layers'
  | 'local_activity'
  | 'share_location'
  | 'emergency'
  | 'north_east'
  | 'add_location'
  | 'fastfood'
  | 'navigation'
  | 'warehouse'
  | 'person_pin'
  | 'local_parking'
  | 'home_repair service'
  | 'local_hospital'
  | 'local_police'
  | 'south'
  | 'zoom_out map'
  | 'location_searching'
  | 'local_florist'
  | 'location_away'
  | 'crisis_alert'
  | 'west'
  | 'local_gas station'
  | 'park'
  | 'maps_ugc'
  | 'cleaning_services'
  | 'local_atm'
  | '360'
  | 'package'
  | 'electrical_services'
  | 'flag_circle'
  | 'north'
  | 'add_location alt'
  | 'directions'
  | 'fmd_bad'
  | 'theater_comedy'
  | 'local_drink'
  | 'location_home'
  | 'local_pizza'
  | 'not_listed location'
  | 'local_post office'
  | 'wine_bar'
  | 'beenhere'
  | 'signpost'
  | 'local_convenience store'
  | 'alt_route'
  | 'tour'
  | 'traffic'
  | 'trip_origin'
  | 'church'
  | 'local_laundry service'
  | 'safety_check'
  | 'ev_station'
  | 'takeout_dining'
  | 'moving'
  | 'zoom_in map'
  | 'soup_kitchen'
  | 'pest_control'
  | 'stadium'
  | 'transfer_within a station'
  | 'location_off'
  | 'connecting_airports'
  | 'wrong_location'
  | 'multiple_stop'
  | 'edit_location'
  | 'plumbing'
  | 'mode_of travel'
  | 'minor_crash'
  | 'south_east'
  | 'local_pharmacy'
  | 'add_road'
  | 'fire_truck'
  | 'castle'
  | 'dry_cleaning'
  | 'set_meal'
  | 'baby_changing station'
  | 'edit_location alt'
  | 'layers_clear'
  | 'north_west'
  | 'mosque'
  | 'edit_attributes'
  | 'local_car wash'
  | 'run_circle'
  | 'transit_enterexit'
  | 'sos'
  | 'satellite'
  | 'edit_road'
  | 'south_west'
  | 'streetview'
  | 'add_home'
  | 'kebab_dining'
  | 'airline_stops'
  | 'fire_hydrant'
  | 'local_see'
  | 'assist_walker'
  | 'add_home work'
  | 'flight_class'
  | 'remove_road'
  | 'no_meals'
  | 'synagogue'
  | 'fort'
  | 'temple_buddhist'
  | 'location_disabled'
  | 'compass_calibration'
  | 'temple_hindu'
  | 'explore_off'
  | 'pest_control rodent'
  | 'directions_alt'
  | 'near_me disabled'
  | 'pergola'
  | 'directions_off'
  | 'things_to do'
  | 'pet_supplies'
  | 'directions_alt off'
  | 'explore_nearby'
  | 'package_2'
  | 'universal_local'
  | 'file_map'
  | 'moved_location'
  | 'move_location'
  | 'safety_check off'
  | 'moving_ministry'
  | 'move'
  | 'description'
  | 'content_copy'
  | 'dashboard'
  | 'edit_note'
  | 'menu_book'
  | 'grid_view'
  | 'list'
  | 'folder'
  | 'list_alt'
  | 'inventory'
  | 'folder_open'
  | 'article'
  | 'fact_check'
  | 'attach_file'
  | 'format_list bulleted'
  | 'assignment'
  | 'task'
  | 'checklist'
  | 'cloud_upload'
  | 'draft'
  | 'summarize'
  | 'cloud'
  | 'draw'
  | 'feed'
  | 'newspaper'
  | 'view_list'
  | 'file_copy'
  | 'note_add'
  | 'border_color'
  | 'book'
  | 'history_edu'
  | 'design_services'
  | 'pending_actions'
  | 'format_quote'
  | 'post_add'
  | 'request_quote'
  | 'cloud_download'
  | 'drag_handle'
  | 'table'
  | 'contact_page'
  | 'archive'
  | 'space_dashboard'
  | 'content_paste'
  | 'percent'
  | 'attachment'
  | 'assignment_ind'
  | 'format_list numbered'
  | 'assignment_turned in'
  | 'tag'
  | 'table_chart'
  | 'dashboard_customize'
  | 'sticky_note 2'
  | 'text_fields'
  | 'format_bold'
  | 'reorder'
  | 'integration_instructions'
  | 'find_in page'
  | 'text_snippet'
  | 'note'
  | 'document_scanner'
  | 'checklist_rtl'
  | 'note_alt'
  | 'edit_document'
  | 'cloud_sync'
  | 'table_rows'
  | 'perm_media'
  | 'cloud_done'
  | 'title'
  | 'table_view'
  | 'content_cut'
  | 'data_object'
  | 'notes'
  | 'cut'
  | 'subject'
  | 'functions'
  | 'format_italic'
  | 'content_paste search'
  | 'format_color fill'
  | 'folder_shared'
  | 'plagiarism'
  | 'horizontal_rule'
  | 'file_present'
  | 'folder_copy'
  | 'cloud_off'
  | 'format_paint'
  | 'ballot'
  | 'team_dashboard'
  | 'format_align left'
  | 'view_column'
  | 'add_link'
  | 'difference'
  | 'read_more'
  | 'view_agenda'
  | 'format_size'
  | 'format_underlined'
  | 'toc'
  | 'vertical_align top'
  | 'height'
  | 'vertical_align bottom'
  | 'view_week'
  | 'copy_all'
  | 'drive_folder upload'
  | 'assignment_late'
  | 'format_color text'
  | 'drive_file move'
  | 'low_priority'
  | 'view_module'
  | 'assignment_return'
  | 'folder_special'
  | 'segment'
  | 'format_align center'
  | 'calendar_view month'
  | 'folder_zip'
  | 'square'
  | 'polyline'
  | 'breaking_news alt 1'
  | 'format_align right'
  | 'grading'
  | 'view_headline'
  | 'linear_scale'
  | 'edit_off'
  | 'view_quilt'
  | 'view_carousel'
  | 'text_increase'
  | 'request_page'
  | 'view_sidebar'
  | 'text_format'
  | 'pages'
  | 'format_align justify'
  | 'calendar_view week'
  | 'numbers'
  | 'hexagon'
  | 'docs_add on'
  | 'folder_delete'
  | 'forms_add on'
  | 'format_shapes'
  | 'imagesearch_roller'
  | 'calendar_view day'
  | 'video_file'
  | 'font_download'
  | 'format_list numbered rtl'
  | 'add_to drive'
  | 'join_inner'
  | 'content_paste go'
  | 'restore_page'
  | 'rectangle'
  | 'format_color reset'
  | 'vertical_split'
  | 'rule_folder'
  | 'view_stream'
  | 'cloud_circle'
  | 'format_indent increase'
  | 'spellcheck'
  | 'data_array'
  | 'assignment_returned'
  | 'align_horizontal left'
  | 'pivot_table chart'
  | 'text_decrease'
  | 'deselect'
  | 'pentagon'
  | 'vertical_align center'
  | 'space_bar'
  | 'merge_type'
  | 'format_strikethrough'
  | 'short_text'
  | 'view_day'
  | 'flip_to front'
  | 'join_left'
  | 'border_all'
  | 'shape_line'
  | 'format_line spacing'
  | 'line_weight'
  | 'horizontal_split'
  | 'format_indent decrease'
  | 'join_right'
  | 'align_horizontal center'
  | 'subtitles_off'
  | 'snippet_folder'
  | 'align_vertical bottom'
  | 'folder_off'
  | 'glyphs'
  | 'format_clear'
  | 'align_horizontal right'
  | 'function'
  | 'vertical_distribute'
  | 'insert_page break'
  | 'content_paste off'
  | 'line_axis'
  | 'superscript'
  | 'horizontal_distribute'
  | 'line_style'
  | 'flip_to back'
  | 'align_vertical center'
  | 'align_vertical top'
  | 'counter_1'
  | 'margin'
  | 'clarify'
  | 'wrap_text'
  | 'subscript'
  | 'view_array'
  | 'ink_pen'
  | 'border_style'
  | 'border_clear'
  | 'amp_stories'
  | 'border_outer'
  | 'ink_eraser'
  | 'type_specimen'
  | 'newsmode'
  | 'text_rotate vertical'
  | 'padding'
  | 'forms_apps script'
  | 'border_vertical'
  | 'text_rotation none'
  | 'format_textdirection l to r'
  | 'docs_apps script'
  | 'ink_highlighter'
  | 'format_overline'
  | 'border_horizontal'
  | 'font_download off'
  | 'finance_chip'
  | 'format_textdirection r to l'
  | 'news'
  | 'text_rotation angleup'
  | 'border_bottom'
  | 'text_rotation down'
  | 'border_inner'
  | 'border_left'
  | 'border_top'
  | 'assignment_add'
  | 'text_rotation angledown'
  | 'equal'
  | 'text_rotate up'
  | 'border_right'
  | 'format_h1'
  | 'note_stack add'
  | 'frame_inspect'
  | 'join'
  | 'counter_2'
  | 'view_column 2'
  | 'note_stack'
  | 'overview'
  | 'full_coverage'
  | 'colors'
  | 'signature'
  | 'export_notes'
  | 'slide_library'
  | 'breaking_news'
  | 'format_underlined squiggle'
  | 'counter_3'
  | 'lab_profile'
  | 'format_h2'
  | 'format_list bulleted add'
  | 'format_paragraph'
  | 'variables'
  | 'format_image left'
  | 'csv'
  | 'file_save'
  | 'reset_image'
  | 'rubric'
  | 'width'
  | 'format_image right'
  | 'ink_marker'
  | 'draw_abstract'
  | 'format_ink highlighter'
  | 'remove_selection'
  | 'format_h3'
  | 'text_fields alt'
  | 'process_chart'
  | 'contract_edit'
  | 'counter_4'
  | 'shapes'
  | 'contract'
  | 'format_h5'
  | 'format_h6'
  | 'unknown_document'
  | 'select'
  | 'voting_chip'
  | 'dictionary'
  | 'scan_delete'
  | 'add_notes'
  | 'diagnosis'
  | 'format_h4'
  | 'location_chip'
  | 'stylus_laser pointer'
  | 'frame_source'
  | 'sticky_note'
  | 'article_shortcut'
  | 'grid_guides'
  | 'tab_duplicate'
  | 'folder_managed'
  | 'regular_expression'
  | 'table_chart view'
  | 'text_ad'
  | 'cell_merge'
  | 'lasso_select'
  | 'list_alt add'
  | 'smb_share'
  | 'stock_media'
  | 'table_rows narrow'
  | 'counter_5'
  | 'business_chip'
  | 'format_letter spacing standard'
  | 'match_case'
  | 'source_notes'
  | 'text_select move forward character'
  | 'ungroup'
  | 'format_text overflow'
  | 'line_end circle'
  | 'book_2'
  | 'custom_typography'
  | 'decimal_increase'
  | 'insert_text'
  | 'scan'
  | 'tab_group'
  | 'line_end arrow'
  | 'counter_6'
  | 'folder_supervised'
  | 'line_end'
  | 'line_start'
  | 'thumbnail_bar'
  | 'format_letter spacing'
  | 'format_letter spacing 2'
  | 'ink_highlighter move'
  | 'line_curve'
  | 'line_end arrow notch'
  | 'tab_close'
  | 'draw_collage'
  | 'stroke_full'
  | 'contract_delete'
  | 'counter_0'
  | 'other_admission'
  | 'text_select start'
  | 'top_panel close'
  | 'counter_7'
  | 'counter_8'
  | 'counter_9'
  | 'highlighter_size 3'
  | 'line_end square'
  | 'stroke_partial'
  | 'text_select jump to beginning'
  | 'flex_wrap'
  | 'heap_snapshot thumbnail'
  | 'language_chinese quick'
  | 'language_spanish'
  | 'line_end diamond'
  | 'line_start diamond'
  | 'post'
  | 'fit_width'
  | 'format_letter spacing wide'
  | 'format_letter spacing wider'
  | 'heap_snapshot multiple'
  | 'line_start circle'
  | 'match_word'
  | 'person_book'
  | 'attach_file add'
  | 'file_save off'
  | 'flex_direction'
  | 'heap_snapshot large'
  | 'ink_eraser off'
  | 'language_korean latin'
  | 'line_start arrow'
  | 'markdown_copy'
  | 'special_character'
  | 'tab_move'
  | 'tab_new right'
  | 'top_panel open'
  | 'tsv'
  | 'align_justify space around'
  | 'align_justify space between'
  | 'align_space between'
  | 'book_5'
  | 'format_text clip'
  | 'frame_reload'
  | 'language_french'
  | 'language_international'
  | 'pageless'
  | 'pen_size 5'
  | 'text_select jump to end'
  | 'text_select move forward word'
  | 'align_justify space even'
  | 'book_3'
  | 'folder_data'
  | 'language_gb english'
  | 'line_start square'
  | 'pen_size 2'
  | 'sheets_rtl'
  | 'tab_close right'
  | 'tab_recent'
  | 'text_select move back word'
  | 'text_select move up'
  | 'two_pager'
  | 'align_center'
  | 'align_flex center'
  | 'decimal_decrease'
  | 'fit_page'
  | 'highlighter_size 5'
  | 'language_chinese dayi'
  | 'language_chinese wubi'
  | 'language_pinyin'
  | 'letter_switch'
  | 'line_start arrow notch'
  | 'pen_size 3'
  | 'text_select move down'
  | 'align_flex start'
  | 'align_justify center'
  | 'align_justify flex end'
  | 'align_justify flex start'
  | 'align_self stretch'
  | 'align_space around'
  | 'align_space even'
  | 'asterisk'
  | 'book_4'
  | 'format_text wrap'
  | 'highlighter_size 4'
  | 'language_chinese array'
  | 'language_chinese cangjie'
  | 'language_chinese pinyin'
  | 'language_us'
  | 'language_us colemak'
  | 'language_us dvorak'
  | 'markdown'
  | 'pen_size 4'
  | 'text_select end'
  | 'text_select move back character'
  | 'variable_add'
  | 'align_end'
  | 'align_flex end'
  | 'align_items stretch'
  | 'align_justify stretch'
  | 'align_start'
  | 'align_stretch'
  | 'flex_no wrap'
  | 'highlighter_size 1'
  | 'highlighter_size 2'
  | 'language_japanese kana'
  | 'markdown_paste'
  | 'pen_size 1'
  | 'variable_insert'
  | 'variable_remove'
  | 'play_arrow'
  | 'play_circle'
  | 'mic'
  | 'videocam'
  | 'volume_up'
  | 'pause'
  | 'music_note'
  | 'library_books'
  | 'movie'
  | 'speed'
  | 'skip_next'
  | 'replay'
  | 'volume_off'
  | 'pause_circle'
  | 'view_in ar'
  | 'fiber_manual record'
  | 'skip_previous'
  | 'stop_circle'
  | 'stop'
  | 'equalizer'
  | 'subscriptions'
  | 'video_library'
  | 'fast_forward'
  | 'playlist_add'
  | 'video_call'
  | 'repeat'
  | 'volume_mute'
  | 'shuffle'
  | 'mic_off'
  | 'hearing'
  | 'library_music'
  | 'playlist_add check'
  | 'podcasts'
  | 'fast_rewind'
  | 'queue_music'
  | 'sound_detection dog barking'
  | 'video_camera front'
  | 'subtitles'
  | 'volume_down'
  | 'play_pause'
  | 'album'
  | 'radio'
  | 'discover_tune'
  | 'av_timer'
  | 'library_add check'
  | 'closed_caption'
  | 'videocam_off'
  | 'stream'
  | 'forward_10'
  | 'not_started'
  | 'replay_10'
  | 'fiber_new'
  | 'playlist_play'
  | 'branding_watermark'
  | 'text_to speech'
  | 'recent_actors'
  | 'playlist_remove'
  | 'interpreter_mode'
  | 'slow_motion video'
  | 'frame_person'
  | 'playlist_add check circle'
  | 'settings_voice'
  | 'video_settings'
  | 'featured_play list'
  | 'sound_detection loud sound'
  | 'audio_file'
  | 'lyrics'
  | 'play_lesson'
  | 'hd'
  | 'repeat_one'
  | 'call_to action'
  | 'high_quality'
  | 'add_to queue'
  | 'music_off'
  | 'video_camera back'
  | 'spatial_audio off'
  | 'shuffle_on'
  | 'playlist_add circle'
  | 'volume_down alt'
  | 'hearing_disabled'
  | 'featured_video'
  | 'replay_5'
  | 'repeat_on'
  | 'queue_play next'
  | 'speech_to text'
  | 'spatial_audio'
  | 'art_track'
  | 'explicit'
  | 'airplay'
  | '4k'
  | 'forward_30'
  | 'forward_5'
  | 'music_video'
  | 'replay_30'
  | 'spatial_tracking'
  | 'control_camera'
  | 'closed_caption disabled'
  | 'digital_out of home'
  | 'brand_awareness'
  | 'video_label'
  | 'fiber_smart record'
  | 'play_disabled'
  | 'repeat_one on'
  | 'broadcast_on personal'
  | 'sd'
  | 'missed_video call'
  | 'surround_sound'
  | 'fiber_pin'
  | '10k'
  | '60fps'
  | 'sound_detection glass break'
  | 'remove_from queue'
  | 'broadcast_on home'
  | 'fiber_dvr'
  | '30fps'
  | '4k_plus'
  | 'video_stable'
  | '8k'
  | '1k'
  | 'instant_mix'
  | 'privacy'
  | '8k_plus'
  | '2k'
  | '7k'
  | '1k_plus'
  | '9k_plus'
  | '9k'
  | '5k'
  | '6k'
  | '2k_plus'
  | '5k_plus'
  | '6k_plus'
  | '3k'
  | '3k_plus'
  | '7k_plus'
  | 'voice_selection'
  | 'ar_on you'
  | 'music_cast'
  | 'no_sound'
  | 'video_search'
  | 'genres'
  | 'hangout_video'
  | 'cinematic_blur'
  | 'media_link'
  | 'video_camera front off'
  | 'artist'
  | 'autoplay'
  | 'movie_edit'
  | 'mic_double'
  | 'autopause'
  | 'forward_media'
  | 'resume'
  | 'ar_stickers'
  | 'movie_info'
  | 'select_to speak'
  | 'audio_description'
  | 'full_hd'
  | '2d'
  | 'hangout_video off'
  | 'autostop'
  | 'forward_circle'
  | 'frame_person off'
  | 'sound_sampler'
  | 'view_in ar off'
  | 'local_shipping'
  | 'directions_car'
  | 'flight'
  | 'directions_run'
  | 'directions_walk'
  | 'flight_takeoff'
  | 'directions_bus'
  | 'train'
  | 'directions_bike'
  | 'airport_shuttle'
  | 'pedal_bike'
  | 'directions_boat'
  | 'two_wheeler'
  | 'agriculture'
  | 'local_taxi'
  | 'sailing'
  | 'electric_car'
  | 'flight_land'
  | 'hail'
  | 'no_crash'
  | 'commute'
  | 'motorcycle'
  | 'car_crash'
  | 'tram'
  | 'departure_board'
  | 'subway'
  | 'electric_moped'
  | 'turn_right'
  | 'electric_scooter'
  | 'fork_right'
  | 'directions_subway'
  | 'tire_repair'
  | 'electric_bike'
  | 'rv_hookup'
  | 'bus_alert'
  | 'turn_left'
  | 'transportation'
  | 'airlines'
  | 'taxi_alert'
  | 'u_turn left'
  | 'directions_railway'
  | 'electric_rickshaw'
  | 'turn_slight right'
  | 'u_turn right'
  | 'fork_left'
  | 'railway_alert'
  | 'bike_scooter'
  | 'turn_sharp right'
  | 'turn_slight left'
  | 'no_transfer'
  | 'snowmobile'
  | 'turn_sharp left'
  | 'flightsmode'
  | 'swap_driving apps wheel'
  | 'swap_driving apps'
  | 'auto_towing'
  | 'ambulance'
  | 'auto_transmission'
  | 'school'
  | 'campaign'
  | 'construction'
  | 'engineering'
  | 'volunteer_activism'
  | 'science'
  | 'sports_esports'
  | 'confirmation_number'
  | 'real_estate agent'
  | 'cake'
  | 'self_improvement'
  | 'sports_soccer'
  | 'air'
  | 'biotech'
  | 'water'
  | 'hiking'
  | 'architecture'
  | 'sports_score'
  | 'personal_injury'
  | 'sports_basketball'
  | 'waves'
  | 'theaters'
  | 'sports_tennis'
  | 'switch_account'
  | 'nights_stay'
  | 'sports_gymnastics'
  | 'how_to vote'
  | 'sports_motorsports'
  | 'backpack'
  | 'surfing'
  | 'sports_kabaddi'
  | 'piano'
  | 'experiment'
  | 'sports'
  | 'toys'
  | 'sports_volleyball'
  | 'camping'
  | 'sports_baseball'
  | 'sports_martial arts'
  | 'swords'
  | 'downhill_skiing'
  | 'scoreboard'
  | 'kayaking'
  | 'phishing'
  | 'sports_handball'
  | 'sports_football'
  | 'skateboarding'
  | 'trophy'
  | 'sports_golf'
  | 'toys_fan'
  | 'sports_cricket'
  | 'nordic_walking'
  | 'roller_skating'
  | 'kitesurfing'
  | 'rowing'
  | 'scuba_diving'
  | 'storm'
  | 'sports_mma'
  | 'featured_seasonal and gifts'
  | 'paragliding'
  | 'snowboarding'
  | 'sports_hockey'
  | 'ice_skating'
  | 'snowshoeing'
  | 'sports_rugby'
  | 'sledding'
  | 'family_link'
  | 'piano_off'
  | 'no_backpack'
  | 'rewarded_ads'
  | 'ifl'
  | 'steps'
  | 'sprint'
  | 'ecg_heart'
  | 'health_metrics'
  | 'toys_and games'
  | 'mindfulness'
  | 'readiness_score'
  | 'cake_add'
  | 'service_toolbox'
  | 'exercise'
  | 'stress_management'
  | 'laps'
  | 'sports_and outdoors'
  | 'person_celebrate'
  | 'person_play'
  | 'floor'
  | 'newsstand'
  | 'menstrual_health'
  | 'azm'
  | 'relax'
  | 'distance'
  | 'pace'
  | 'avg_pace'
  | 'bath_private'
  | 'play_shapes'
  | 'water_medium'
  | 'avg_time'
  | 'interactive_space'
  | 'water_full'
  | 'bath_outdoor'
  | 'onsen'
  | 'eda'
  | 'fertile'
  | 'spo2'
  | 'podiatry'
  | 'elevation'
  | 'bia'
  | 'cleaning'
  | 'glass_cup'
  | 'hr_resting'
  | 'science_off'
  | 'bath_public large'
  | 'water_loss'
  | 'check_in out'
  | 'monitor_weight loss'
  | 'sauna'
  | 'monitor_weight gain'
  | 'physical_therapy'
  | 'sleep_score'
  | 'phone_iphone'
  | 'save'
  | 'smartphone'
  | 'print'
  | 'keyboard_arrow down'
  | 'computer'
  | 'devices'
  | 'desktop_windows'
  | 'smart_display'
  | 'dns'
  | 'keyboard_backspace'
  | 'headphones'
  | 'smart_toy'
  | 'phone_android'
  | 'memory'
  | 'keyboard_arrow right'
  | 'keyboard'
  | 'live_tv'
  | 'laptop_mac'
  | 'tv'
  | 'headset_mic'
  | 'keyboard_arrow up'
  | 'device_thermostat'
  | 'balance'
  | 'mouse'
  | 'route'
  | 'point_of sale'
  | 'keyboard_arrow left'
  | 'laptop_chromebook'
  | 'keyboard_return'
  | 'watch'
  | 'power'
  | 'laptop_windows'
  | 'router'
  | 'developer_board'
  | 'display_settings'
  | 'scale'
  | 'cast'
  | 'book_online'
  | 'developer_mode'
  | 'fax'
  | 'videogame_asset'
  | 'cast_for education'
  | 'device_hub'
  | 'straight'
  | 'screen_search desktop'
  | 'mobile_friendly'
  | 'desktop_mac'
  | 'settings_input antenna'
  | 'settings_ethernet'
  | 'monitor'
  | 'devices_other'
  | 'send_to mobile'
  | 'important_devices'
  | 'tablet_mac'
  | 'system_update'
  | 'settings_remote'
  | 'monitor_weight'
  | 'screen_rotation'
  | 'screen_share'
  | 'keyboard_alt'
  | 'settings_input component'
  | 'sim_card'
  | 'speaker'
  | 'merge'
  | 'tablet'
  | 'connected_tv'
  | 'vibration'
  | 'keyboard_tab'
  | 'power_off'
  | 'screenshot_monitor'
  | 'remember_me'
  | 'browser_updated'
  | 'security_update good'
  | 'sd_card'
  | 'cast_connected'
  | 'device_unknown'
  | 'tablet_android'
  | 'charging_station'
  | 'phonelink_setup'
  | 'punch_clock'
  | 'screenshot'
  | 'scanner'
  | 'settings_input hdmi'
  | 'stay_current portrait'
  | 'tap_and play'
  | 'keyboard_hide'
  | 'print_disabled'
  | 'security_update warning'
  | 'keyboard_capslock'
  | 'speaker_group'
  | 'disc_full'
  | 'app_blocking'
  | 'mobile_screen share'
  | 'aod'
  | 'sd_card alert'
  | 'tty'
  | 'add_to home screen'
  | 'lift_to talk'
  | 'earbuds'
  | 'perm_device information'
  | 'stop_screen share'
  | 'mobile_off'
  | 'headset_off'
  | 'desktop_access disabled'
  | 'screen_lock portrait'
  | 'reset_tv'
  | 'offline_share'
  | 'adf_scanner'
  | 'headphones_battery'
  | 'dock'
  | 'roundabout_right'
  | 'settop_component'
  | 'watch_off'
  | 'settings_input svideo'
  | 'smart_screen'
  | 'stay_current landscape'
  | 'chromecast_device'
  | 'settings_cell'
  | 'home_max'
  | 'earbuds_battery'
  | 'power_input'
  | 'no_sim'
  | 'ramp_right'
  | 'screen_lock landscape'
  | 'roundabout_left'
  | 'stay_primary portrait'
  | 'stay_primary landscape'
  | 'developer_board off'
  | 'tv_off'
  | 'home_mini'
  | 'phonelink_off'
  | 'open_in phone'
  | 'ramp_left'
  | 'screen_lock rotation'
  | 'videogame_asset off'
  | 'aod_tablet'
  | 'gamepad'
  | 'robot'
  | 'devices_wearables'
  | 'google_home devices'
  | 'robot_2'
  | 'rear_camera'
  | 'jamboard_kiosk'
  | 'tv_options edit channels'
  | 'joystick'
  | 'app_promo'
  | 'developer_mode tv'
  | 'mimo'
  | 'touchpad_mouse'
  | 'memory_alt'
  | 'mimo_disconnect'
  | 'tv_options input settings'
  | 'camera_video'
  | 'tv_signin'
  | 'devices_off'
  | 'lightning_stand'
  | 'aod_watch'
  | 'tv_guide'
  | 'hard_drive'
  | 'ecg'
  | 'night_sight max'
  | 'general_device'
  | 'reset_wrench'
  | 'assistant_device'
  | 'missing_controller'
  | 'stream_apps'
  | 'keyboard_tab rtl'
  | 'open_jam'
  | 'cast_warning'
  | 'deskphone'
  | 'screenshot_tablet'
  | 'cast_pause'
  | 'hard_drive 2'
  | 'pacemaker'
  | 'tv_remote'
  | 'watch_wake'
  | 'audio_video receiver'
  | 'lda'
  | 'print_connect'
  | 'print_error'
  | 'p2p'
  | 'print_add'
  | 'print_lock'
  | 'ventilator'
  | 'watch_button press'
  | 'security_key'
  | 'dark_mode'
  | 'light_mode'
  | 'wifi'
  | 'signal_cellular alt'
  | 'password'
  | 'widgets'
  | 'android'
  | 'storage'
  | 'pin'
  | 'rss_feed'
  | 'battery_full'
  | 'wifi_off'
  | 'bluetooth'
  | 'battery_charging full'
  | 'thermostat'
  | 'dvr'
  | 'graphic_eq'
  | 'nightlight'
  | 'battery_5 bar'
  | 'signal_wifi 4 bar'
  | 'gpp_maybe'
  | 'cable'
  | 'gpp_bad'
  | 'data_usage'
  | 'battery_4 bar'
  | 'signal_cellular 4 bar'
  | 'radar'
  | 'battery_full alt'
  | 'airplanemode_active'
  | 'cameraswitch'
  | 'battery_0 bar'
  | 'wallpaper'
  | 'flashlight_on'
  | 'signal_disconnected'
  | 'network_check'
  | 'battery_6 bar'
  | 'charger'
  | 'wifi_tethering'
  | 'sim_card download'
  | 'usb'
  | 'quick_phrases'
  | 'splitscreen'
  | 'adb'
  | 'battery_3 bar'
  | 'battery_1 bar'
  | 'network_wifi 3 bar'
  | 'battery_low'
  | 'battery_alert'
  | 'network_wifi'
  | 'bluetooth_searching'
  | 'bluetooth_connected'
  | 'wifi_find'
  | '5g'
  | 'battery_2 bar'
  | 'brightness_high'
  | 'network_cell'
  | 'nfc'
  | 'pattern'
  | 'data_saver on'
  | 'bluetooth_disabled'
  | 'signal_wifi statusbar not connected'
  | 'signal_cellular 3 bar'
  | 'signal_wifi bad'
  | 'network_wifi 2 bar'
  | 'network_wifi 1 bar'
  | 'noise_control off'
  | 'brightness_medium'
  | 'signal_wifi off'
  | 'mode_standby'
  | 'brightness_low'
  | 'battery_very low'
  | 'mobiledata_off'
  | 'signal_wifi 0 bar'
  | 'battery_charging 80'
  | 'battery_charging 20'
  | 'battery_saver'
  | 'grid_4x4'
  | 'battery_charging 90'
  | 'flashlight_off'
  | 'signal_wifi statusbar null'
  | 'battery_charging 50'
  | 'settings_system daydream'
  | 'battery_unknown'
  | 'signal_cellular 2 bar'
  | 'screen_rotation alt'
  | 'signal_cellular 1 bar'
  | 'wifi_calling 3'
  | 'wifi_lock'
  | '4g_mobiledata'
  | 'badge_critical battery'
  | 'noise_aware'
  | 'do_not disturb on total silence'
  | 'battery_charging 60'
  | 'signal_cellular connected no internet 0 bar'
  | 'nearby_error'
  | 'signal_cellular 0 bar'
  | 'battery_charging 30'
  | 'network_ping'
  | 'signal_cellular connected no internet 4 bar'
  | 'wifi_tethering error'
  | 'brightness_auto'
  | 'edgesensor_high'
  | 'wifi_calling 1'
  | '1x_mobiledata'
  | 'signal_cellular nodata'
  | 'wifi_2 bar'
  | 'grid_3x3'
  | 'lte_mobiledata'
  | 'airplanemode_inactive'
  | 'perm_data setting'
  | 'signal_cellular alt 2 bar'
  | 'devices_fold'
  | 'bluetooth_drive'
  | 'perm_scan wifi'
  | 'network_locked'
  | '4g_plus mobiledata'
  | 'media_bluetooth on'
  | 'wifi_calling 2'
  | 'signal_cellular off'
  | 'timer_10 select'
  | 'wifi_tethering off'
  | 'edgesensor_low'
  | 'signal_cellular alt 1 bar'
  | 'wifi_1 bar'
  | '3g_mobiledata'
  | 'usb_off'
  | 'apk_install'
  | 'signal_cellular null'
  | 'lte_plus mobiledata'
  | 'ios'
  | 'grid_goldenratio'
  | 'g_mobiledata'
  | 'portable_wifi off'
  | 'noise_control on'
  | 'media_bluetooth off'
  | 'timer_3 select'
  | 'apk_document'
  | 'e_mobiledata'
  | 'nearby_off'
  | 'h_mobiledata'
  | 'r_mobiledata'
  | 'h_plus mobiledata'
  | 'dock_to left'
  | 'dual_screen'
  | 'stylus_note'
  | 'bigtop_updates'
  | 'stylus'
  | 'nearby'
  | 'overview_key'
  | 'dock_to right'
  | 'screenshot_region'
  | 'brightness_alert'
  | 'screenshot_frame'
  | 'screen_record'
  | 'brightness_empty'
  | 'display_external input'
  | 'network_wifi 3 bar locked'
  | 'battery_status good'
  | 'keyboard_keys'
  | 'splitscreen_right'
  | 'splitscreen_left'
  | 'screenshot_keyboard'
  | 'keyboard_external input'
  | 'magnify_docked'
  | 'battery_error'
  | 'screen_rotation up'
  | '1x_mobiledata badge'
  | 'magnify_fullscreen'
  | 'wallpaper_slideshow'
  | 'dock_to bottom'
  | 'keyboard_off'
  | 'network_wifi 2 bar locked'
  | 'network_wifi locked'
  | 'battery_plus'
  | 'keyboard_capslock badge'
  | '5g_mobiledata badge'
  | 'backlight_low'
  | 'battery_change'
  | 'network_wifi 1 bar locked'
  | 'keyboard_full'
  | 'wifi_home'
  | 'wifi_notification'
  | 'backlight_high'
  | 'h_plus mobiledata badge'
  | 'keyboard_onscreen'
  | 'keyboard_previous language'
  | 'lte_mobiledata badge'
  | 'splitscreen_bottom'
  | 'splitscreen_top'
  | '3g_mobiledata badge'
  | '4g_mobiledata badge'
  | 'e_mobiledata badge'
  | 'g_mobiledata badge'
  | 'grid_3x3 off'
  | 'h_mobiledata badge'
  | 'lte_plus mobiledata badge'
  | 'battery_share'
  | 'ev_mobiledata badge'
  | 'signal_cellular pause'
  | 'badge'
  | 'verified_user'
  | 'admin_panel settings'
  | 'report'
  | 'security'
  | 'vpn_key'
  | 'shield'
  | 'policy'
  | 'exclamation'
  | 'privacy_tip'
  | 'assured_workload'
  | 'vpn_lock'
  | 'disabled_visible'
  | 'e911_emergency'
  | 'enhanced_encryption'
  | 'private_connectivity'
  | 'vpn_key off'
  | 'add_moderator'
  | 'encrypted'
  | 'no_encryption'
  | 'sync_lock'
  | 'wifi_password'
  | 'key_visualizer'
  | 'remove_moderator'
  | 'passkey'
  | 'report_off'
  | 'shield_lock'
  | 'shield_person'
  | 'shield_locked'
  | 'vpn_key alert'
  | 'shield_question'
  | 'apartment'
  | 'location_city'
  | 'fitness_center'
  | 'lunch_dining'
  | 'spa'
  | 'cottage'
  | 'local_cafe'
  | 'hotel'
  | 'family_restroom'
  | 'beach_access'
  | 'local_bar'
  | 'pool'
  | 'other_houses'
  | 'luggage'
  | 'liquor'
  | 'casino'
  | 'airplane_ticket'
  | 'room_service'
  | 'sports_bar'
  | 'bakery_dining'
  | 'ramen_dining'
  | 'nightlife'
  | 'local_dining'
  | 'holiday_village'
  | 'icecream'
  | 'escalator_warning'
  | 'dinner_dining'
  | 'museum'
  | 'food_bank'
  | 'night_shelter'
  | 'festival'
  | 'attractions'
  | 'golf_course'
  | 'stairs'
  | 'villa'
  | 'smoke_free'
  | 'smoking_rooms'
  | 'car_rental'
  | 'airline_seat recline normal'
  | 'elevator'
  | 'gite'
  | 'child_friendly'
  | 'airline_seat recline extra'
  | 'breakfast_dining'
  | 'carpenter'
  | 'car_repair'
  | 'cabin'
  | 'brunch_dining'
  | 'do_not touch'
  | 'no_food'
  | 'houseboat'
  | 'tapas'
  | 'rice_bowl'
  | 'wheelchair_pickup'
  | 'bento'
  | 'no_drinks'
  | 'do_not step'
  | 'airline_seat flat'
  | 'bungalow'
  | 'escalator'
  | 'airline_seat individual suite'
  | 'chalet'
  | 'no_luggage'
  | 'travel'
  | 'airline_seat legroom extra'
  | 'airline_seat flat angled'
  | 'airline_seat legroom normal'
  | 'airline_seat legroom reduced'
  | 'no_stroller'
  | 'flights_and hotels'
  | 'personal_places'
  | 'trip'
  | 'travel_luggage and bags'
  | 'personal_bag'
  | 'checked_bag'
  | 'concierge'
  | 'personal_bag question'
  | 'carry_on bag question'
  | 'your_trips'
  | 'checked_bag question'
  | 'carry_on bag checked'
  | 'carry_on bag'
  | 'personal_bag off'
  | 'carry_on bag inactive'
  | 'house'
  | 'bed'
  | 'ac_unit'
  | 'chair'
  | 'electric_bolt'
  | 'coffee'
  | 'sensors'
  | 'child_care'
  | 'back_hand'
  | 'emergency_home'
  | 'checkroom'
  | 'grass'
  | 'shower'
  | 'mode_fan'
  | 'mop'
  | 'kitchen'
  | 'thermometer'
  | 'styler'
  | 'yard'
  | 'bathtub'
  | 'king_bed'
  | 'roofing'
  | 'energy_savings leaf'
  | 'window'
  | 'valve'
  | 'cooking'
  | 'garage_home'
  | 'door_front'
  | 'mode_heat'
  | 'light'
  | 'foundation'
  | 'garage'
  | 'outdoor_grill'
  | 'table_restaurant'
  | 'dining'
  | 'sensor_occupied'
  | 'deck'
  | 'weekend'
  | 'coffee_maker'
  | 'humidity_high'
  | 'flatware'
  | 'highlight'
  | 'fireplace'
  | 'humidity_low'
  | 'mode_night'
  | 'electric_meter'
  | 'tv_gen'
  | 'humidity_mid'
  | 'bedroom_parent'
  | 'chair_alt'
  | 'blender'
  | 'scene'
  | 'microwave'
  | 'heat_pump'
  | 'bedroom_baby'
  | 'single_bed'
  | 'oven_gen'
  | 'bathroom'
  | 'hardware'
  | 'in_home mode'
  | 'hot_tub'
  | 'mode_off on'
  | 'sprinkler'
  | 'table_bar'
  | 'gas_meter'
  | 'mode_cool'
  | 'crib'
  | 'propane_tank'
  | 'soap'
  | 'living'
  | 'countertops'
  | 'home_iot device'
  | 'fire_extinguisher'
  | 'outlet'
  | 'gate'
  | 'remote_gen'
  | 'matter'
  | 'sensor_door'
  | 'event_seat'
  | 'airware'
  | 'faucet'
  | 'dishwasher_gen'
  | 'air_freshener'
  | 'energy_program saving'
  | 'balcony'
  | 'water_damage'
  | 'wash'
  | 'camera_indoor'
  | 'bedroom_child'
  | 'house_siding'
  | 'switch'
  | 'microwave_gen'
  | 'detector_smoke'
  | 'door_sliding'
  | 'iron'
  | 'energy_program time used'
  | 'desk'
  | 'umbrella'
  | 'water_heater'
  | 'fence'
  | 'dresser'
  | 'doorbell'
  | 'door_back'
  | 'mode_fan off'
  | 'hvac'
  | 'emergency_share'
  | 'kettle'
  | 'camera_outdoor'
  | 'air_purifier gen'
  | 'emergency_heat'
  | 'stroller'
  | 'curtains'
  | 'multicooker'
  | 'shield_moon'
  | 'sensors_off'
  | 'mode_heat cool'
  | 'emergency_recording'
  | 'thermostat_auto'
  | 'smart_outlet'
  | 'controller_gen'
  | 'blinds'
  | 'roller_shades'
  | 'dry'
  | 'blinds_closed'
  | 'roller_shades closed'
  | 'propane'
  | 'sensor_window'
  | 'apparel'
  | 'thermostat_carbon'
  | 'range_hood'
  | 'tv_with assistant'
  | 'doorbell_3p'
  | 'blanket'
  | 'vertical_shades closed'
  | 'vertical_shades'
  | 'curtains_closed'
  | 'mode_heat off'
  | 'mode_cool off'
  | 'family_home'
  | 'health_and beauty'
  | 'tamper_detection off'
  | 'grocery'
  | 'light_off'
  | 'shelves'
  | 'household_supplies'
  | 'vacuum'
  | 'wall_art'
  | 'garage_door'
  | 'dishwasher'
  | 'home_and garden'
  | 'thermometer_add'
  | 'thermometer_gain'
  | 'air_purifier'
  | 'home_improvement and tools'
  | 'oven'
  | 'thermometer_loss'
  | 'hallway'
  | 'skillet'
  | 'thermometer_minus'
  | 'emergency_share off'
  | 'stockpot'
  | 'skillet_cooktop'
  | 'stadia_controller'
  | 'door_open'
  | 'nest_eco leaf'
  | 'device_reset'
  | 'nest_remote comfort sensor'
  | 'nest_clock farsight analog'
  | 'laundry'
  | 'battery_horiz 075'
  | 'shield_with heart'
  | 'temp_preferences eco'
  | 'familiar_face and zone'
  | 'tools_power drill'
  | 'airwave'
  | 'productivity'
  | 'battery_horiz 050'
  | 'nest_heat link gen 3'
  | 'nest_display'
  | 'weather_snowy'
  | 'ev_charger'
  | 'activity_zone'
  | 'nest_remote'
  | 'cleaning_bucket'
  | 'settings_alert'
  | 'nest_cam indoor'
  | 'arrows_more up'
  | 'home_storage'
  | 'nest_heat link e'
  | 'nest_multi room'
  | 'nest_secure alarm'
  | 'battery_horiz 000'
  | 'light_group'
  | 'nest_cam outdoor'
  | 'google_wifi'
  | 'detection_and zone'
  | 'nest_thermostat gen 3'
  | 'mfg_nest yale lock'
  | 'tools_pliers wire stripper'
  | 'detector_alarm'
  | 'early_on'
  | 'tools_ladder'
  | 'nest_cam iq outdoor'
  | 'nest_mini'
  | 'floor_lamp'
  | 'nest_cam iq'
  | 'nest_clock farsight digital'
  | 'home_speaker'
  | 'nest_hello doorbell'
  | 'nest_audio'
  | 'home_max dots'
  | 'motion_sensor active'
  | 'nest_wifi router'
  | 'cool_to dry'
  | 'house_with shield'
  | 'zone_person urgent'
  | 'nest_display max'
  | 'nest_farsight weather'
  | 'shield_with house'
  | 'chromecast_2'
  | 'battery_profile'
  | 'heat_pump balance'
  | 'window_closed'
  | 'arming_countdown'
  | 'nest_found savings'
  | 'self_care'
  | 'detector_status'
  | 'window_open'
  | 'tools_level'
  | 'nest_thermostat zirconium eu'
  | 'zone_person alert'
  | 'arrows_more down'
  | 'nest_true radiant'
  | 'detector'
  | 'nest_cam wired stand'
  | 'nest_detect'
  | 'climate_mini split'
  | 'door_sensor'
  | 'nest_wifi point'
  | 'nest_doorbell visitor'
  | 'nest_cam floodlight'
  | 'nest_tag'
  | 'quiet_time'
  | 'tools_installation kit'
  | 'nest_connect'
  | 'nest_thermostat sensor'
  | 'nest_thermostat sensor eu'
  | 'nest_sunblock'
  | 'tools_phillips'
  | 'doorbell_chime'
  | 'nest_thermostat e eu'
  | 'detector_co'
  | 'table_lamp'
  | 'detector_battery'
  | 'tools_flat head'
  | 'nest_wake on approach'
  | 'nest_wake on press'
  | 'motion_sensor urgent'
  | 'motion_sensor alert'
  | 'window_sensor'
  | 'tamper_detection on'
  | 'nest_cam magnet mount'
  | 'zone_person idle'
  | 'quiet_time active'
  | 'nest_cam stand'
  | 'nest_cam wall mount'
  | 'wall_lamp'
  | 'detector_offline'
  | 'motion_sensor idle'
  | 'water_pump'
  | 'sensors_krx'
  | 'nest_thermostat'
  | 'heat'
  | 'assistant_on hub'
  | 'mode_dual'
  | 'nest_protect'
  | 'aq_indoor'
  | 'on_hub device'
  | 'google_tv remote'
  | 'aq'
  | 'sensors_krx off'
  | 'nest_wifi pro'
  | 'nest_wifi pro 2'
  | 'farsight_digital'
  | 'humidity_indoor'
  | 'nest_gale wifi';
