export type __PrimitiveType = string | number | boolean | object;

export type PropertyOptions<T extends __PrimitiveType> = {
  propertyName?: string;
  type?: string;
  objectType?: string;
  required?: boolean;
  isArray?: boolean;
  unique?: boolean;
  modelName?: string;
  relationName?: string;
  relationType: string;
  format?: string;
  description?: string;
  defaultValue?: T;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  enums?: T[];
  update?: boolean;
  inView?: boolean;
  strict?: boolean;
  before?: string;
  after?: string;
  inweek?: boolean;
  weekend?: boolean;
  between?: [string, string];
  days?: number[];
  day?: number;
  monthdays?: number[];
  inputType?: string;
  searchable?: boolean;
  excludeFromView?: boolean;
};
