// @index('./*', f => `export * from '${f.path}'`)
export * from './autocomplete.spec'
export * from './autocomplete'
export * from './color'
export * from './element-ref'
export * from './icon-variant'
export * from './icon.spec'
export * from './icons'
export * from './input-type.spec'
export * from './input-type'
export * from './menu-item'
export * from './template-ref'
export * from './toggle'
