// @index(['./*', '!./*.spec.ts'], f => `export * from '${f.path}'`)
export * from './app-config.provider'
export * from './date-filter.provider'
export * from './date-selection-strategy.provider'
export * from './form.provider'
export * from './input-filter.provider'
export * from './nav-item.provider'
export * from './provide-entity-name.provider'
export * from './table.provider'
export * from './view.provider'
