// @index('./*', f => `export * from '${f.path}'`)
export * from './address'
export * from './comment'
export * from './counter'
export * from './email'
export * from './img'
export * from './link'
export * from './phone'
export * from './record'
export * from './review'
export * from './tag'
