// @index('./*', f => `export * from '${f.path}'`)
export * from './auth'
export * from './blog'
export * from './common'
export * from './customer'
export * from './inventory'
export * from './job'
export * from './order'
export * from './project'
export * from './question'
