// @index('./*', f => `export * from '${f.path}'`)
export * from './address'
export * from './comment'
export * from './counter'
export * from './email'
export * from './img'
export * from './link'
export * from './log'
export * from './phone'
export * from './query'
export * from './range'
export * from './record'
export * from './review'
export * from './tag'
export * from './value'
